"""TS-02 through TS-08 manual cases."""
from case_util import c


def ts02_cases():
    return [
        c("TS-02-001", "Login Page", "Login page loads for anonymous user", "P0", "Positive",
          "Logged out.", "Anonymous", "URL: /login",
          "1. Open /login.",
          "Form shows mobile + password. Link to signup and forgot password. No redirect loop.",
          "GET /login"),
        c("TS-02-002", "Login", "Valid SUPER_ADMIN login succeeds", "P0", "Positive",
          "U-H1-SUPER exists (TS-01-012). Verified + active.", "SUPER_ADMIN",
          "Mobile: 9876500002\nPassword: ApexAdmin@1",
          "1. Enter mobile + password.\n2. Submit.",
          "200 {ok, role:SUPER_ADMIN, sessionToken, redirectTo:'/'}. Cookie mederp_session set (48h idle, httpOnly, SameSite=strict). Lands on /. Audit LOGIN.",
          "POST /api/auth/login"),
        c("TS-02-003", "Login", "Login accepts identifier alias instead of mobile", "P1", "Positive",
          "U-H1-SUPER exists.", "SUPER_ADMIN",
          '{"identifier":"9876500002","password":"ApexAdmin@1"}',
          "1. POST login with identifier field (API or if UI uses it).",
          "200 success — same as mobile field.",
          "POST /api/auth/login"),
        c("TS-02-004", "Login", "Wrong password returns generic 401", "P0", "Negative",
          "U-H1-SUPER exists.", "Anonymous",
          "Mobile: 9876500002\nPassword: WrongPass9",
          "1. Submit wrong password.",
          "401 'Invalid mobile number or password.' No session. Audit LOGIN_FAILED. Does not reveal if mobile exists.",
          "POST /api/auth/login"),
        c("TS-02-005", "Login", "Unknown mobile returns same generic 401", "P0", "Security",
          "—", "Anonymous", "Mobile: 9000000099\nPassword: Anything1",
          "1. Submit unknown mobile.",
          "401 same message as wrong password (no enumeration).",
          "POST /api/auth/login"),
        c("TS-02-006", "Login", "Invalid mobile format rejected 400", "P1", "Boundary",
          "—", "Anonymous", "Mobile: 123\nPassword: Password1",
          "1. Submit.",
          "400 'Enter a valid 10-digit mobile number and password.'",
          "POST /api/auth/login"),
        c("TS-02-007", "Login", "Unverified user blocked with needsOtp", "P0", "Negative",
          "Create user via signup without verifying OTP (use fresh mobile).", "Anonymous",
          "Mobile from TS-03 signup before verify\nPassword: used at signup",
          "1. Attempt login before OTP verify.",
          "403 {error:'Mobile is not verified yet.', needsOtp:true, mobile}. UI should send to /signup/verify.",
          "POST /api/auth/login"),
        c("TS-02-008", "Login", "Inactive user blocked 403", "P0", "Negative",
          "Deactivate a staff user in TS-06 (or set isActive=false).", "Anonymous",
          "Inactive user mobile/password",
          "1. Login as inactive user.",
          "403 'This account is inactive. Contact hospital admin.' Sessions cleared if any.",
          "POST /api/auth/login"),
        c("TS-02-009", "Login", "Inactive hospital blocks hospital-staff login", "P0", "Negative",
          "SOFTWARE_ADMIN sets H1 isActive=false (TS-05).", "SUPER_ADMIN",
          "U-H1-SUPER credentials",
          "1. Login after hospital stopped.",
          "403 'This hospital's access has been stopped. Contact MedERP support.' Existing sessions invalidated.",
          "POST /api/auth/login"),
        c("TS-02-010", "Login", "HELPDESK login redirects to /helpdesk", "P1", "Positive",
          "HELPDESK user exists (TS-05).", "HELPDESK",
          "Helpdesk mobile/password",
          "1. Login as HELPDESK.",
          "200 redirectTo=/helpdesk. Lands on helpdesk queue.",
          "POST /api/auth/login"),
        c("TS-02-011", "Login", "Staff without hospital redirects to /join", "P0", "Positive",
          "Verified signup user with hospitalId=null.", "RECEPTIONIST",
          "Fresh verified signup credentials",
          "1. Login.",
          "redirectTo=/join. User sees hospital join page.",
          "POST /api/auth/login"),
        c("TS-02-012", "OTP", "Dummy OTP 123456 verifies when OTP_DUMMY≠0", "P0", "Positive",
          "OTP_DUMMY≠0. Unverified user with issued OTP (or dummy).", "Anonymous",
          "Mobile: (signup)\nOTP: 123456",
          "1. POST verify-otp with 123456.",
          "200 {ok:true}. isVerified=true. OTP fields cleared.",
          "POST /api/auth/verify-otp"),
        c("TS-02-013", "OTP", "Wrong OTP returns Invalid OTP", "P0", "Negative",
          "Active OTP issued (real or dummy mode with wrong code).", "Anonymous",
          "OTP: 000000",
          "1. Submit wrong OTP once.",
          "400 'Invalid OTP.' Attempts incremented.",
          "POST /api/auth/verify-otp"),
        c("TS-02-014", "OTP", "5 wrong OTP attempts lock — must re-request", "P0", "Negative",
          "OTP_DUMMY=0 with real OTP, OR force attempt counter via API.", "Anonymous",
          "5× wrong OTP",
          "1. Submit wrong OTP five times.",
          "After 5th: 400 'Too many incorrect OTP attempts. Request a new one.' OTP cleared (locked).",
          "POST /api/auth/verify-otp"),
        c("TS-02-015", "OTP", "Expired OTP message after TTL", "P1", "Boundary",
          "OTP issued; wait >10 minutes OR set otpExpiresAt in past in DB.", "Anonymous",
          "Any OTP",
          "1. Verify after expiry.",
          "400 'OTP has expired. Request a new one.'",
          "POST /api/auth/verify-otp"),
        c("TS-02-016", "Forgot Password", "Forgot password always returns 200 (anti-enumeration)", "P0", "Security",
          "—", "Anonymous",
          "A) known mobile 9876500002\nB) unknown 9000000099",
          "1. Submit forgot for known mobile.\n2. Submit forgot for unknown.",
          "Both 200 with same message: 'If that mobile number is registered, an OTP has been sent.' OTP only created for active known user.",
          "POST /api/auth/forgot-password"),
        c("TS-02-017", "Reset Password", "Valid OTP resets password and kills all sessions", "P0", "Positive",
          "Issue forgot OTP for U-H1-SUPER. Have an active session in another browser.", "SUPER_ADMIN",
          "Mobile: 9876500002\nOTP: 123456 (dummy)\nNew password: ApexAdmin@2",
          "1. Login in browser A.\n2. Reset password via OTP.\n3. Refresh browser A.\n4. Login with new password.",
          "Reset 200 ok. Old sessions deleted. Browser A logged out. New password works. isVerified=true.",
          "POST /api/auth/reset-password"),
        c("TS-02-018", "Reset Password", "Reset with invalid OTP fails", "P0", "Negative",
          "Forgot requested.", "Anonymous",
          "OTP: 111111\nPassword: NewPass12",
          "1. Submit reset with bad OTP.",
          "400 Invalid/expired OTP. Password unchanged.",
          "POST /api/auth/reset-password"),
        c("TS-02-019", "Reset Password", "New password <8 chars rejected", "P1", "Boundary",
          "Valid OTP available.", "Anonymous",
          "OTP: 123456\nPassword: short",
          "1. Submit.",
          "400 password min 8 chars. Password unchanged.",
          "POST /api/auth/reset-password"),
        c("TS-02-020", "Logout", "Logout clears cookie and DB session", "P0", "Positive",
          "Logged in.", "Any",
          "—",
          "1. Logout.\n2. Hit a protected page.",
          "200 {ok:true}. Cookie cleared. Redirect to /login. Audit LOGOUT. Protected routes require login again.",
          "POST /api/auth/logout"),
        c("TS-02-021", "Session", "Idle session >48h is rejected and deleted", "P1", "Boundary",
          "Create session with expiresAt in past (DB) or wait 48h with no activity.", "Any",
          "Stale mederp_session cookie",
          "1. Request protected API/page with expired session.",
          "Treated as logged out. Session row deleted. Cookie cleared. Redirect /login.",
          "Session load (session-user.ts)"),
        c("TS-02-022", "Session", "Bearer Authorization token works like cookie", "P2", "Positive",
          "Login and capture sessionToken from response.", "SUPER_ADMIN",
          "Authorization: Bearer <sessionToken>",
          "1. Call a protected API with Bearer, no cookie.",
          "Request authorized as that user.",
          "Any hospital API"),
        c("TS-02-023", "Rate Limit", "Login rate limit 10 / 15 min returns 429", "P1", "Security",
          "Fresh IP / process. Use wrong password to avoid lockout side effects.", "Anonymous",
          "11 rapid failed logins",
          "1. POST login 11 times quickly with wrong password.",
          "After limit: 429 'Too many login attempts. Try again in N seconds.' (lock 15 min).",
          "POST /api/auth/login"),
        c("TS-02-024", "Rate Limit", "Forgot-password rate limit 5 / 15 min (lock 30 min)", "P1", "Security",
          "Fresh IP.", "Anonymous",
          "6 rapid forgot-password requests",
          "1. Hit forgot-password 6 times.",
          "429 after 5. Lock window 30 minutes.",
          "POST /api/auth/forgot-password"),
        c("TS-02-025", "Rate Limit", "Signup rate limit 8 / 60 min", "P2", "Security",
          "Fresh IP.", "Anonymous",
          "9 signup attempts",
          "1. POST signup repeatedly.",
          "429 after 8 within 60 min.",
          "POST /api/auth/signup"),
        c("TS-02-026", "Middleware", "Unauthenticated user redirected to /login?next=", "P0", "Positive",
          "Logged out.", "Anonymous",
          "URL: /patients",
          "1. Open /patients.",
          "Redirect to /login?next=/patients (or with search).",
          "middleware.ts"),
        c("TS-02-027", "Middleware", "Logged-in user hitting /login redirects home", "P1", "Positive",
          "Logged in as SUPER_ADMIN.", "SUPER_ADMIN",
          "/login",
          "1. Open /login while authenticated.",
          "Redirect to /.",
          "middleware.ts"),
        c("TS-02-028", "Middleware", "Public routes accessible without session", "P0", "Positive",
          "Logged out.", "Anonymous",
          "/login, /signup, /signup/verify, /forgot-password, /register-hospital, /terms",
          "1. Open each public page.",
          "All load without login. /api/auth/* and /api/public/* and /api/health reachable.",
          "middleware.ts"),
        c("TS-02-029", "Watchlist", "Document /forgot-password/reset middleware behavior", "P1", "Security",
          "Logged out. Have reset OTP.", "Anonymous",
          "/forgot-password/reset",
          "1. Open reset page while logged out with OTP flow from UI.\n2. Note if redirected to login.",
          "Record actual behavior vs Watchlist W-08. If reset requires session unexpectedly → Fail + Defect.",
          "GET /forgot-password/reset"),
        c("TS-02-030", "Mobile Normalize", "Login with 91-prefixed mobile works", "P1", "Boundary",
          "User mobile stored as 9876500002.", "SUPER_ADMIN",
          "Mobile: 919876500002\nPassword: current",
          "1. Login with 91 prefix.",
          "Normalized to 10 digits; login succeeds.",
          "POST /api/auth/login"),
        c("TS-02-031", "Session Cap", "Third login evicts the least-recently-used session", "P0", "Positive",
          "Same user signed in on two devices.", "SUPER_ADMIN",
          "Device A idle, Device B recently used, Device C new login",
          "1. Login on A.\n2. Login on B (use B).\n3. Login on C.",
          "C succeeds. A session row deleted (LRU). B still valid. Max 2 AppSession rows. A next request → login.",
          "createSession extraSessionIds"),
        c("TS-02-032", "Session Slide", "Activity within 48h does not require re-login", "P0", "Positive",
          "Logged in. Use the app (page load or ping) before 48h idle.", "Any",
          "POST /api/session/ping while tab visible",
          "1. Stay signed in and use the app / wait 15 min with tab visible.\n2. Continue working past 48h from original login.",
          "lastSeenAt and expiresAt slide (throttle 5 min). Cookie re-issued. No login screen.",
          "GET/POST /api/session/ping + session-user"),
        c("TS-02-033", "Session Idle", "More than 48h idle requires sign-in", "P0", "Negative",
          "Last activity >48h ago.", "Any",
          "Stale session",
          "1. Open any protected page.",
          "Must sign in again. AppShell/ping clear the cookie to avoid a login redirect loop.",
          "AppShell + /api/session/ping"),
    ]


def ts03_cases():
    return [
        c("TS-03-001", "Signup Page", "Signup page loads and lists staff roles only", "P0", "Positive",
          "Logged out.", "Anonymous", "/signup",
          "1. Open /signup.\n2. Inspect role dropdown.",
          "Roles available: DOCTOR, NURSE, RECEPTIONIST, PHARMACIST, LAB_TECH, ACCOUNTANT. No SUPER_ADMIN / SOFTWARE_ADMIN / HELPDESK.",
          "GET /signup"),
        c("TS-03-002", "Signup", "Happy path creates unverified user and sends OTP", "P0", "Positive",
          "Username/mobile unused.", "Anonymous",
          "Username: joindoctor1\nMobile: 9876503001\nPassword: JoinDoc@12\nRole: DOCTOR",
          "1. Submit signup.",
          "200 ok. Message to enter OTP then join hospital. User isVerified=false, hospitalId=null. Redirect/UI to verify.",
          "POST /api/auth/signup"),
        c("TS-03-003", "Signup", "Duplicate username or mobile returns 409", "P0", "Negative",
          "joindoctor1 exists.", "Anonymous",
          "Same username or same mobile as TS-03-002",
          "1. Signup with duplicate.",
          "409 'Username or mobile number is already registered.'",
          "POST /api/auth/signup"),
        c("TS-03-004", "Signup", "Username validation (min 3, allowed charset)", "P1", "Boundary",
          "—", "Anonymous",
          "A) username: ab\nB) username: bad name!",
          "1. Attempt both.",
          "400 for both (min 3; /^[a-zA-Z0-9._]+$/).",
          "POST /api/auth/signup"),
        c("TS-03-005", "Verify", "OTP verify then login lands on /join", "P0", "Positive",
          "TS-03-002 user exists.", "DOCTOR",
          "Mobile: 9876503001\nOTP: 123456",
          "1. Verify OTP.\n2. Login.",
          "Verify 200. Login redirectTo=/join.",
          "POST /api/auth/verify-otp → login"),
        c("TS-03-006", "Join", "Submit join request to active hospital", "P0", "Positive",
          "Logged in as joindoctor1. H1 active.", "DOCTOR",
          "hospitalId: H1\nrole: DOCTOR\nnote: optional",
          "1. Open /join.\n2. Select H1 + DOCTOR.\n3. Submit.",
          "200. Join request PENDING. SUPER_ADMINs of H1 + SOFTWARE_ADMINs notified.",
          "POST /api/join-requests"),
        c("TS-03-007", "Join", "Duplicate pending join to same hospital blocked", "P0", "Negative",
          "TS-03-006 pending exists.", "DOCTOR",
          "Same hospital again",
          "1. Submit second join to H1.",
          "409 duplicate pending.",
          "POST /api/join-requests"),
        c("TS-03-008", "Join", "Platform account cannot join hospital", "P0", "RBAC",
          "Logged in as SOFTWARE_ADMIN or HELPDESK.", "SOFTWARE_ADMIN",
          "Any hospitalId",
          "1. POST join-requests.",
          "403 'Platform accounts cannot join a hospital.'",
          "POST /api/join-requests"),
        c("TS-03-009", "Join", "User already in a hospital cannot join another", "P0", "Negative",
          "U-H1-SUPER logged in.", "SUPER_ADMIN",
          "Another hospital",
          "1. Attempt join.",
          "409 already has hospital.",
          "POST /api/join-requests"),
        c("TS-03-010", "Approve", "SUPER_ADMIN approves join — assigns hospital, codes, doctor staff", "P0", "Positive",
          "Pending DOCTOR join for H1. Seats available. Logged in as U-H1-SUPER.", "SUPER_ADMIN",
          "action: approve",
          "1. Open /hospital/join-requests.\n2. Approve.",
          "User hospitalId=H1, role=DOCTOR, userCode+employeeId allocated. Doctor Staff created. Other pending requests for user auto-rejected. User notified. Audit HOSPITAL_JOIN_APPROVED.",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-011", "Approve", "SOFTWARE_ADMIN can approve any hospital join", "P1", "Positive",
          "Pending join for any hospital. Login U-SAAS.", "SOFTWARE_ADMIN",
          "action: approve",
          "1. /platform/join-requests → Approve.",
          "Same success effects as hospital approve.",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-012", "Reject", "Reject notifies requester", "P0", "Positive",
          "Create another pending join (new signup).", "SUPER_ADMIN",
          "action: reject\nnote: optional",
          "1. Reject request.",
          "Status REJECTED. Requester notified. User still hospitalId=null.",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-013", "Cancel", "Requester can cancel own pending request", "P1", "Positive",
          "User with PENDING request, logged in as requester.", "NURSE",
          "action: cancel",
          "1. Cancel from /join.",
          "Status REJECTED with note 'Cancelled by requester.'",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-014", "Module Gate", "PHARMACIST join blocked on CLINIC tier (no pharmacy)", "P0", "Negative",
          "H1 on CLINIC (pharmacyEnabled=false). Pending PHARMACIST join.", "SUPER_ADMIN",
          "role PHARMACIST approve",
          "1. Approve PHARMACIST on CLINIC.",
          "403 module not enabled for pharmacy.",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-015", "Module Gate", "LAB_TECH join blocked when labEnabled=false", "P0", "Negative",
          "H1 labEnabled=false.", "SUPER_ADMIN",
          "LAB_TECH approve",
          "1. Approve LAB_TECH.",
          "403 lab module not enabled.",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-016", "Seats", "Approve blocked when staff seat limit reached", "P0", "Negative",
          "CLINIC seatLimit=3 filled including SUPER_ADMIN (create via TS-06).", "SUPER_ADMIN",
          "New pending join approve",
          "1. Approve when seats full.",
          "403 seat limit (assertStaffSeatAvailable).",
          "PATCH /api/join-requests/[id]"),
        c("TS-03-017", "Visibility", "GET join-requests scoped by role", "P1", "RBAC",
          "Requests exist across hospitals.", "Various",
          "—",
          "1. GET as SOFTWARE_ADMIN, SUPER_ADMIN, staff requester.",
          "SOFTWARE_ADMIN: all. SUPER_ADMIN: own hospital. Others: own requests only.",
          "GET /api/join-requests"),
        c("TS-03-018", "Inactive Hospital", "Cannot join inactive hospital", "P1", "Negative",
          "Hospital isActive=false.", "DOCTOR (no hospital)",
          "inactive hospitalId",
          "1. Submit join.",
          "Error — hospital must be active.",
          "POST /api/join-requests"),
    ]


def ts04_cases():
    return [
        c("TS-04-001", "Tiers", "Three OPD plans — prices and seats", "P0", "Positive",
          "—", "Any",
          "CLINIC Plan1 ₹2499 / 3 seats (admin included; e.g. 1 admin doctor + 2 nurses/receptionists);\n"
          "STARTER Plan2 ₹4499 / 6 seats (admin included);\n"
          "GROWTH Plan3 ₹5999 / 9 seats (admin included)",
          "1. Compare UI (/register-hospital or /hospital/subscription) to table.",
          "Matches subscription-tiers.ts. SUPER_ADMIN counts as one seat. Admin-as-doctor and nurse-as-receptionist do not add seats. No pharmacy/lab/wards/inventory on any plan.",
          "GET /api/public/package"),
        c("TS-04-002", "Trial Access", "During trial hospital staff can use app normally", "P0", "Positive",
          "H1 trialEndsAt in future.", "RECEPTIONIST",
          "—",
          "1. Login and open /patients.",
          "Access allowed. No 402 TRIAL_ENDED.",
          "requireHospitalActor"),
        c("TS-04-003", "Trial Expiry", "Expired trial without paid sub blocks hospital APIs with 402", "P0", "Negative",
          "Set H1 trialEndsAt to past; no ACTIVE/AUTHENTICATED/PENDING subscription with valid period.", "RECEPTIONIST",
          "—",
          "1. Login as receptionist.\n2. Call hospital API e.g. GET patients.",
          "402 {code:'TRIAL_ENDED'}. UI redirects staff to /subscribe.",
          "hospital-access.ts"),
        c("TS-04-004", "Trial Expiry", "SUPER_ADMIN redirected to /hospital/subscription on expiry", "P0", "Positive",
          "Same expired trial H1.", "SUPER_ADMIN",
          "—",
          "1. Login as super admin.\n2. Browse app.",
          "Redirected to /hospital/subscription (not only /subscribe). Can still hit subscription APIs.",
          "/hospital/subscription"),
        c("TS-04-005", "Trial Expiry", "Allowed paths during expiry: subscribe + auth + subscription APIs", "P1", "Positive",
          "Expired trial.", "SUPER_ADMIN",
          "/subscribe, /hospital/subscription, /api/hospital/subscription*",
          "1. Open allowed paths.\n2. Open /patients.",
          "Allowed paths work. /patients blocked/redirected.",
          "hospital-access.ts"),
        c("TS-04-006", "Legacy", "Hospital with trialEndsAt=null is never auto-blocked by trial logic", "P1", "Positive",
          "Legacy hospital trialEndsAt null, no subscription.", "RECEPTIONIST",
          "—",
          "1. Use hospital APIs.",
          "Access allowed (legacy never blocked by trial).",
          "hospital-access.ts"),
        c("TS-04-007", "Module Gate", "All current plans hide pharmacy/lab/wards/inventory nav", "P0", "Positive",
          "H1 on CLINIC / STARTER / GROWTH.", "SUPER_ADMIN",
          "—",
          "1. Inspect main nav on each plan.",
          "Pharmacy, Lab, Wards, Inventory links hidden / inaccessible on every current plan.",
          "Nav + hospitalFieldsFromTier"),
        c("TS-04-008", "Module Gate", "Register UI never offers pharmacy/lab/wards/inventory upsell", "P0", "Positive",
          "Anonymous on /register-hospital.", "Anonymous",
          "—",
          "1. Review plan cards and package JSON.",
          "No module toggles. publicSubscriptionTiers omits pharmacyEnabled/labEnabled/wardsEnabled.",
          "GET /api/public/package"),
        c("TS-04-009", "Start Sub", "SUPER_ADMIN start subscription create phase returns checkout", "P0", "Positive",
          "Razorpay configured. SUPER_ADMIN. No blocking active subscription.", "SUPER_ADMIN",
          "POST /api/hospital/subscription/start phase=create, tierId=STARTER",
          "1. Start subscription from UI.",
          "Checkout params returned (keyId, subscriptionId/orderId, amount=3500).",
          "POST /api/hospital/subscription/start"),
        c("TS-04-010", "Start Sub", "Confirm phase after payment activates subscription + PAID invoice", "P0", "Positive",
          "Checkout success from TS-04-009. SUPER_ADMIN has a valid mobile.", "SUPER_ADMIN",
          "phase=confirm + razorpay ids/signature",
          "1. Complete confirm.",
          "HospitalSubscription ACTIVE. Platform invoice PAID. Access restored if previously expired. First successful charge also WhatsApps subscription_bill to SUPER_ADMIN (same path as monthly renewal; webhook dedupes if it fires too).",
          "POST /api/hospital/subscription/start"),
        c("TS-04-011", "Start Sub", "Cannot start second subscription while one active", "P1", "Negative",
          "Active subscription exists.", "SUPER_ADMIN",
          "phase=create again",
          "1. Attempt start again.",
          "409 already linked.",
          "POST /api/hospital/subscription/start"),
        c("TS-04-012", "Schedule Change", "Tier change schedules at cycle end (not immediate entitlements)", "P0", "Positive",
          "Active Razorpay subscription.", "SUPER_ADMIN",
          "action=schedule tierId=GROWTH (Plan 3 ₹4999)",
          "1. Schedule upgrade.",
          "pendingSubscriptionTier set. Current entitlements unchanged until charged webhook / cycle end.",
          "POST /api/hospital/subscription"),
        c("TS-04-013", "Cancel", "Cancel at cycle end keeps access until period end", "P0", "Positive",
          "Active subscription.", "SUPER_ADMIN",
          "action=cancel atCycleEnd=true (default)",
          "1. Cancel.",
          "cancelAtPeriodEnd true. Access continues until currentPeriodEnd.",
          "POST /api/hospital/subscription"),
        c("TS-04-014", "Webhook", "subscription.charged creates PAID invoice; dedupes by razorpayPaymentId", "P0", "Positive",
          "Webhook secret set. Known subscription. Hospital SUPER_ADMIN has a 10-digit mobile.", "System",
          "Event subscription.charged (twice same payment id)",
          "1. Send valid signed webhook twice.",
          "First: PAID platform invoice created + subscription_bill WhatsApp to SUPER_ADMIN. Second: no duplicate invoice and no second WhatsApp (dedupe by razorpayPaymentId).",
          "POST /api/public/razorpay/webhook"),
        c("TS-04-015", "Webhook", "Invalid webhook signature rejected", "P0", "Security",
          "Webhook secret set.", "System",
          "Bad x-razorpay-signature",
          "1. POST webhook with wrong signature.",
          "Rejected (4xx). No state change.",
          "POST /api/public/razorpay/webhook"),
        c("TS-04-016", "Webhook", "subscription.cancelled / completed updates local status", "P1", "Positive",
          "Linked subscription.", "System",
          "cancelled / completed events",
          "1. Send event.",
          "Local status updated; cancelledAt set; nextCharge cleared as coded.",
          "POST /api/public/razorpay/webhook"),
        c("TS-04-017", "Platform Tier", "SOFTWARE_ADMIN can change hospital tier + create PAID invoice", "P0", "Positive",
          "Login U-SAAS.", "SOFTWARE_ADMIN",
          "tierId=STARTER paymentMethod=UPI",
          "1. Change tier from platform hospital page.",
          "Entitlements updated (6 seats, modules off). PAID platform invoice ₹3500.",
          "POST /api/platform/hospitals/[id]/subscription"),
        c("TS-04-018", "RBAC", "Non SUPER_ADMIN cannot manage hospital subscription APIs", "P0", "RBAC",
          "Login as DOCTOR.", "DOCTOR",
          "GET/POST subscription",
          "1. Call subscription APIs.",
          "403.",
          "/api/hospital/subscription*"),
        c("TS-04-019", "Active Paid", "Paid ACTIVE subscription allows access even if trialEndsAt past", "P0", "Positive",
          "trialEndsAt past + ACTIVE subscription currentPeriodEnd future.", "RECEPTIONIST",
          "—",
          "1. Use /patients.",
          "Access allowed.",
          "hospital-access.ts"),
        c("TS-04-020", "GET Sub", "GET subscription returns plan, tiers, razorpay status for SUPER_ADMIN", "P1", "Positive",
          "SUPER_ADMIN logged in.", "SUPER_ADMIN",
          "—",
          "1. Open subscription page / GET API.",
          "Shows current tier among Plan 1–3, seat usage, razorpay status. No module upsells.",
          "GET /api/hospital/subscription"),
        c("TS-04-021", "Renewal Bill", "Successful monthly renewal WhatsApps subscription bill to SUPER_ADMIN", "P0", "Positive",
          "AskEva/WhatsApp configured or console fallback. SaaS billing settings filled. Hospital SUPER_ADMIN mobile valid. Active Razorpay subscription.", "System",
          "Event subscription.charged on the renewal date. Template subscription_bill.",
          "1. Wait for / simulate successful Razorpay subscription.charged.\n2. Confirm PlatformInvoice PAID.\n3. Check OutboundMessage + WhatsApp on SUPER_ADMIN mobile.",
          "PDF uses SaaS billing-settings company name/address/GSTIN/bank/terms. Template vars: admin_name, hospital_name, invoice_no, total_amount, billing_period. Recipient is hospital SUPER_ADMIN only — not receptionist, not a doctor-only user. Audit SUBSCRIPTION_BILL_SENT. Charge stays PAID if WhatsApp fails (SUBSCRIPTION_BILL_FAILED).",
          "recordSubscriptionCharge → notifySubscriptionRenewalBill"),
        c("TS-04-022", "Renewal Bill", "Doctor-as-admin still receives the monthly bill on SUPER_ADMIN mobile", "P0", "Positive",
          "Hospital SUPER_ADMIN also practices as doctor (admin-as-doctor). Same user mobile.", "System",
          "SUPER_ADMIN mobile (doctor-admin).",
          "1. Renew subscription successfully.\n2. Confirm WhatsApp destination.",
          "Bill goes to that SUPER_ADMIN number (the doctor-admin). Not a different DOCTOR user. One SUPER_ADMIN per hospital.",
          "platform-invoice-whatsapp.ts"),
        c("TS-04-023", "Renewal Bill", "Missing SUPER_ADMIN mobile skips WhatsApp; invoice still PAID", "P1", "Negative",
          "Hospital SUPER_ADMIN mobile blank/invalid.", "System",
          "subscription.charged",
          "1. Charge subscription.",
          "PlatformInvoice PAID. WhatsApp skipped. Audit SUBSCRIPTION_BILL_SKIPPED. Hospital access not blocked.",
          "notifySubscriptionRenewalBill"),
    ]


def ts05_cases():
    return [
        c("TS-05-001", "Guard", "Only SOFTWARE_ADMIN can open /platform/**", "P0", "RBAC",
          "—", "SUPER_ADMIN / HELPDESK / DOCTOR",
          "/platform/hospitals",
          "1. Login as each non-SOFTWARE_ADMIN.\n2. Open /platform/hospitals.",
          "Redirected away (SUPER_ADMIN → /hospital/audit-log). Cannot use platform console.",
          "platform/layout.tsx"),
        c("TS-05-002", "Hospitals List", "SOFTWARE_ADMIN lists hospitals", "P0", "Positive",
          "U-SAAS logged in.", "SOFTWARE_ADMIN",
          "/platform/hospitals",
          "1. Open list.",
          "Hospitals visible including H1 from TS-01.",
          "GET /platform/hospitals"),
        c("TS-05-003", "Create Hospital", "Platform create hospital — PAID invoice, SUPER_ADMIN pre-verified", "P0", "Positive",
          "Unused phone/username.", "SOFTWARE_ADMIN",
          "Name: Platform Made Clinic\nPhone: 9876505001\nAdmin Username: platmadeadm\nAdmin Mobile: 9876505002\nPassword: Password1\nTier: CLINIC",
          "1. /platform/hospitals/new → submit.",
          "Hospital created. Admin SUPER_ADMIN verified. Invoice PAID (method UPI). No trial required unless set.",
          "POST /api/platform/hospitals"),
        c("TS-05-004", "Edit Hospital", "PATCH name, address, phone, opdFee, extraStaffSlots, trialEndsAt", "P0", "Positive",
          "Hospital from TS-05-003.", "SOFTWARE_ADMIN",
          "opdFee: 450\nextraStaffSlots: 2\ntrialEndsAt: future ISO date",
          "1. Edit hospital detail.\n2. Save.",
          "Fields updated. opdFee≥0. extraStaffSlots 0–500. Audit logged.",
          "PATCH /api/platform/hospitals/[id]"),
        c("TS-05-005", "Stop Access", "isActive=false deactivates hospital users and blocks login", "P0", "Positive",
          "Active hospital with staff.", "SOFTWARE_ADMIN",
          "isActive: false",
          "1. Stop access.\n2. Try staff login.",
          "Hospital inactive. Hospital users deactivated (except platform roles). Login 403 hospital stopped. Sessions killed.",
          "PATCH /api/platform/hospitals/[id]"),
        c("TS-05-006", "Reactivate", "Re-enable hospital and a user restores access", "P1", "Positive",
          "Hospital stopped in TS-05-005.", "SOFTWARE_ADMIN",
          "isActive true + reactivate admin user",
          "1. Set hospital active.\n2. Reactivate SUPER_ADMIN user.\n3. Login.",
          "Login works again.",
          "PATCH hospitals + users"),
        c("TS-05-007", "Users", "List users for a hospital; create user under hospital", "P0", "Positive",
          "H1 active.", "SOFTWARE_ADMIN",
          "/platform/users/[hospitalId]/new",
          "1. Create RECEPTIONIST under H1.",
          "User created in hospital. Appears in list. SOFTWARE_ADMIN users not listed in hospital staff lists.",
          "POST /api/hospital/users (with hospitalId)"),
        c("TS-05-008", "User Merge", "Merge duplicate hospital users", "P0", "Positive",
          "Two duplicate staff users same hospital (create intentionally).", "SOFTWARE_ADMIN",
          "survivorId + duplicateId",
          "1. Merge via platform UI/API.",
          "Duplicate deactivated; mobile→merged-{id}; sessions cleared; related rows moved. Audit STAFF_USER_MERGED.",
          "POST /api/platform/users/[id]/merge"),
        c("TS-05-009", "User Merge", "Cannot merge platform roles", "P1", "Negative",
          "—", "SOFTWARE_ADMIN",
          "Attempt merge involving SOFTWARE_ADMIN/HELPDESK",
          "1. POST merge.",
          "Rejected.",
          "POST /api/platform/users/[id]/merge"),
        c("TS-05-010", "Billing Settings", "GET/PUT platform billing settings", "P1", "Positive",
          "U-SAAS.", "SOFTWARE_ADMIN",
          "companyName, gstin, invoicePrefix, address, bank, terms",
          "1. Open /platform/billing-settings.\n2. Update company details + prefix.\n3. Save.",
          "Settings persist. New subscription invoices use new prefix. Page copy states these details print on every subscription bill WhatsApped to hospital SUPER_ADMIN.",
          "GET/PUT /api/platform/billing-settings"),
        c("TS-05-011", "Invoices", "View platform invoice detail", "P1", "Positive",
          "Invoice from registration exists.", "SOFTWARE_ADMIN",
          "/platform/invoices/[id]",
          "1. Open invoice.",
          "Shows invoiceNo, hospital, status, lines, total, plus SaaS company name/address/GSTIN/bank/terms from billing settings.",
          "platform invoices page"),
        c("TS-05-012", "Helpdesk Team", "Create HELPDESK agent", "P0", "Positive",
          "Unused mobile.", "SOFTWARE_ADMIN",
          "Username: helpdesk01\nMobile: 9999990001\nPassword: Helpdesk@1",
          "1. /platform/helpdesk-team → create.",
          "User role HELPDESK, platform (no hospital). Can login to /helpdesk.",
          "POST /api/platform/helpdesk-users"),
        c("TS-05-013", "Join Requests", "Platform can see and act on all join requests", "P1", "Positive",
          "Pending joins exist.", "SOFTWARE_ADMIN",
          "/platform/join-requests",
          "1. Approve/reject from platform.",
          "Works across hospitals.",
          "GET/PATCH join-requests"),
        c("TS-05-014", "Audit", "Platform audit log hospital picker", "P1", "Positive",
          "—", "SOFTWARE_ADMIN",
          "/platform/audit-log → pick hospital",
          "1. View logs for H1.",
          "Shows hospital audit entries (up to page limit).",
          "/platform/audit-log/[hospitalId]"),
        c("TS-05-015", "Medicine Catalog", "SOFTWARE_ADMIN/HELPDESK can open medicine catalog", "P2", "Positive",
          "—", "SOFTWARE_ADMIN / HELPDESK",
          "/medicine-catalog",
          "1. Open page.",
          "Accessible (catalog management — smoke only; deep pharmacy out of scope).",
          "/medicine-catalog"),
        c("TS-05-016", "RBAC", "HELPDESK cannot create hospitals or change billing settings", "P0", "RBAC",
          "Login helpdesk.", "HELPDESK",
          "POST /api/platform/hospitals\nPUT billing-settings",
          "1. Attempt APIs.",
          "403 / redirected. Cannot access platform hospital admin APIs.",
          "platform APIs"),
        c("TS-05-017", "Code Validation", "Hospital code PATCH must be valid 3–12 A-Z0-9-", "P2", "Boundary",
          "Hospital exists.", "SOFTWARE_ADMIN",
          "code: bad code!!",
          "1. PATCH invalid code.",
          "400 validation error.",
          "PATCH /api/platform/hospitals/[id]"),
        c("TS-05-018", "Subscription", "Platform tier change from hospital detail", "P0", "Positive",
          "Hospital on CLINIC.", "SOFTWARE_ADMIN",
          "tier STARTER (Plan 2) + paymentMethod CASH",
          "1. Change subscription.",
          "Tier fields updated; PAID invoice; seats=6; pharmacy/lab/inventory remain off.",
          "POST .../subscription"),
        c("TS-05-019", "Users List", "Platform users list excludes SOFTWARE_ADMIN accounts", "P2", "Positive",
          "—", "SOFTWARE_ADMIN",
          "/platform/users",
          "1. Browse global/hospital users.",
          "SOFTWARE_ADMIN accounts not shown as hospital staff.",
          "GET /api/platform/users"),
        c("TS-05-020", "Inactive Hospital Create Block", "Cannot use stopped hospital for new staff joins", "P1", "Negative",
          "Hospital inactive.", "SOFTWARE_ADMIN",
          "—",
          "1. Try approve join / create user if UI allows.",
          "Blocked or hospital must be active first.",
          "join / users APIs"),
        c("TS-05-021", "opdFee", "opdFee cannot be negative", "P1", "Boundary",
          "—", "SOFTWARE_ADMIN",
          "opdFee: -10",
          "1. PATCH.",
          "400 / rejected.",
          "PATCH /api/platform/hospitals/[id]"),
        c("TS-05-022", "extraStaffSlots", "extraStaffSlots above 500 rejected", "P2", "Boundary",
          "—", "SOFTWARE_ADMIN",
          "extraStaffSlots: 501",
          "1. PATCH.",
          "Rejected (0–500).",
          "PATCH /api/platform/hospitals/[id]"),
        c("TS-05-023", "Home", "SOFTWARE_ADMIN home shows SaaS console branding", "P2", "Positive",
          "Logged in U-SAAS.", "SOFTWARE_ADMIN",
          "/",
          "1. Open home.",
          "Platform/SaaS console navigation visible (hospitals, users, helpdesk team, etc.).",
          "GET /"),
        c("TS-05-024", "Health", "Health API public", "P2", "Positive",
          "—", "Anonymous",
          "/api/health",
          "1. GET health.",
          "200 healthy response without auth.",
          "GET /api/health"),
        c("TS-05-025", "Billing Settings", "SaaS billing details appear on monthly subscription WhatsApp PDF", "P0", "Positive",
          "Billing settings saved (company name, address, phone, email, GSTIN, bank, terms). Hospital SUPER_ADMIN mobile valid. WhatsApp template subscription_bill approved in AskEva.", "SOFTWARE_ADMIN",
          "Renewal from TS-04-021",
          "1. Confirm billing settings.\n2. Trigger successful subscription.charged.\n3. Open WhatsApp PDF on SUPER_ADMIN phone and /platform/invoices/[id].",
          "PDF letterhead matches billing settings. Bill-to is the hospital. Amount/period match the charge. Recipient is SUPER_ADMIN (doctor-admin uses the same number). Company phone on the form is seller contact, not the WhatsApp destination.",
          "platform-invoice-pdf.ts + subscription_bill"),
    ]


def ts06_cases():
    return [
        c("TS-06-001", "Access", "Only SUPER_ADMIN opens /hospital/users", "P0", "RBAC",
          "H1.", "DOCTOR / RECEPTIONIST",
          "/hospital/users",
          "1. Open as non-super.",
          "Redirected / denied.",
          "/hospital/users"),
        c("TS-06-002", "Create", "Create DOCTOR with all key fields", "P0", "Positive",
          "SUPER_ADMIN. Seats available. Unused mobile.", "SUPER_ADMIN",
          "First: Arjun\nLast: Mehta\nMobile: 9876500011\nPassword: Doctor@123\nRole: DOCTOR\nEmail: doc@apexcare.test\nSpecialization: General Medicine\nMedical Reg: KMC-7788\nConsultation Fee: 500\nFollow-up Fee: 200",
          "1. Add user.\n2. Save.",
          "User created isVerified=true isActive=true. Username auto-suggested (*doc). userCode DOC-NNNNNN. employeeId {CODE}-NNNN. Staff row linked. Audit USER_CREATED.",
          "POST /api/hospital/users"),
        c("TS-06-003", "Create", "Create NURSE, RECEPTIONIST, ACCOUNTANT", "P0", "Positive",
          "Seats available.", "SUPER_ADMIN",
          "Mobiles: 9876500012 / 0013 / 0014\nPasswords: Nurse@123 / Recep@123 / Account@123",
          "1. Create each role.",
          "Each gets Staff profile (non-platform). Username suffixes nur/rec/acc. Codes NUR/REC/ACC.",
          "POST /api/hospital/users"),
        c("TS-06-004", "Validation", "First name required; password min 8; mobile Indian", "P0", "Negative",
          "—", "SUPER_ADMIN",
          "A) empty firstName\nB) password abc\nC) mobile 111",
          "1. Attempt creates.",
          "A) First name required. B) min 8. C) invalid mobile.",
          "POST /api/hospital/users"),
        c("TS-06-005", "Username", "Manual username uniqueness and charset", "P1", "Negative",
          "Doctor username exists.", "SUPER_ADMIN",
          "Duplicate username / username with spaces",
          "1. Create.",
          "409 clash or 400 charset.",
          "POST /api/hospital/users"),
        c("TS-06-006", "Seats", "Create blocked at seat limit (admin included)", "P0", "Negative",
          "CLINIC 3 seats filled including SUPER_ADMIN.", "SUPER_ADMIN",
          "New nurse",
          "1. Create.",
          "403 seat limit. Admin-as-doctor / nurse-as-receptionist do not create extra seats.",
          "POST /api/hospital/users"),
        c("TS-06-007", "Module", "Cannot create PHARMACIST if pharmacyEnabled false", "P0", "Negative",
          "CLINIC hospital.", "SUPER_ADMIN",
          "Role PHARMACIST",
          "1. Create.",
          "403 pharmacy module.",
          "POST /api/hospital/users"),
        c("TS-06-008", "Module", "Cannot create LAB_TECH if labEnabled false", "P0", "Negative",
          "CLINIC.", "SUPER_ADMIN",
          "LAB_TECH",
          "1. Create.",
          "403 lab module.",
          "POST /api/hospital/users"),
        c("TS-06-009", "Roles", "Hospital SUPER_ADMIN cannot assign SUPER_ADMIN via hospital UI", "P0", "RBAC",
          "—", "SUPER_ADMIN",
          "role SUPER_ADMIN on create",
          "1. Try assign SUPER_ADMIN.",
          "Only SOFTWARE_ADMIN may assign SUPER_ADMIN. Hospital admin limited to STAFF_ROLES.",
          "POST /api/hospital/users"),
        c("TS-06-010", "Edit", "Update profile fields and optional password", "P0", "Positive",
          "Doctor exists.", "SUPER_ADMIN",
          "Change consultationFee to 550; set new password Doctor@456",
          "1. Edit user.\n2. Save.",
          "Updated. If password/role/deactivate → sessions invalidated. Audit USER_UPDATED.",
          "PATCH /api/hospital/users/[id]"),
        c("TS-06-011", "Deactivate", "Cannot deactivate self", "P0", "Negative",
          "Logged in as SUPER_ADMIN.", "SUPER_ADMIN",
          "Own user isActive=false",
          "1. Attempt self-disable.",
          "400 blocked.",
          "PATCH /api/hospital/users/[id]"),
        c("TS-06-012", "Deactivate", "Deactivate staff kills sessions and blocks login", "P0", "Positive",
          "RECEPTIONIST logged in elsewhere.", "SUPER_ADMIN",
          "isActive=false",
          "1. Deactivate.\n2. Refresh other session.\n3. Login attempt.",
          "Sessions cleared. Login 403 inactive.",
          "PATCH /api/hospital/users/[id]"),
        c("TS-06-013", "Employment", "employmentStatus INACTIVE forces staff.isActive false", "P1", "Positive",
          "Nurse exists.", "SUPER_ADMIN",
          "employmentStatus: INACTIVE (user isActive still true)",
          "1. Save.",
          "Staff.isActive false even if AppUser active (per employee.ts rule).",
          "PATCH /api/hospital/users/[id]"),
        c("TS-06-014", "Signature", "SUPER_ADMIN uploads signature — becomes ACTIVE; previous REVOKED", "P0", "Positive",
          "Doctor user. PNG/JPG <~300–400KB.", "SUPER_ADMIN",
          "displayName: Dr Arjun Mehta\nimage base64",
          "1. Upload signature on user page.",
          "New UserSignature ACTIVE + verified metadata. Prior ACTIVE → REVOKED. Audit SIGNATURE_UPLOADED.",
          "POST /api/hospital/users/[id]/signature"),
        c("TS-06-015", "Signature", "Staff cannot self-upload signature", "P0", "RBAC",
          "Login as DOCTOR.", "DOCTOR",
          "Own signature upload",
          "1. POST signature.",
          "403 — only SUPER_ADMIN / SOFTWARE_ADMIN.",
          "POST .../signature"),
        c("TS-06-016", "Signature", "Revoke active signature", "P1", "Positive",
          "Active signature exists.", "SUPER_ADMIN",
          "action: revoke",
          "1. Revoke.",
          "Status REVOKED + revokedAt. Audit SIGNATURE_REVOKED.",
          "PATCH .../signature"),
        c("TS-06-017", "Signature", "Oversized / invalid image rejected", "P1", "Boundary",
          "—", "SUPER_ADMIN",
          "Non-image or >max size",
          "1. Upload.",
          "400 sanitize error.",
          "POST .../signature"),
        c("TS-06-018", "Staff Directory", "/staff is read-only for hospital users", "P2", "Positive",
          "Staff exist.", "RECEPTIONIST",
          "/staff",
          "1. Open directory.",
          "List visible; no create controls for receptionist.",
          "GET /staff"),
        c("TS-06-019", "Email", "Email without @ rejected when provided", "P2", "Negative",
          "—", "SUPER_ADMIN",
          "email: notanemail",
          "1. Create/update.",
          "Rejected.",
          "POST/PATCH users"),
        c("TS-06-020", "Lock SUPER", "Cannot change existing SUPER_ADMIN role away (hospital admin)", "P1", "RBAC",
          "Hospital has SUPER_ADMIN user.", "SUPER_ADMIN",
          "Change role to DOCTOR",
          "1. Edit.",
          "Role locked to SUPER_ADMIN for hospital admin edits.",
          "PATCH /api/hospital/users/[id]"),
        c("TS-06-021", "Platform Edit", "SOFTWARE_ADMIN can edit any hospital user including SUPER_ADMIN role", "P1", "Positive",
          "U-SAAS.", "SOFTWARE_ADMIN",
          "Platform user edit page",
          "1. Edit hospital user from platform.",
          "Allowed (broader than hospital admin).",
          "/platform/users/..."),
        c("TS-06-022", "Codes Backfill", "Missing userCode/employeeId backfilled on users page load", "P2", "Positive",
          "Legacy user without codes if available.", "SUPER_ADMIN",
          "/hospital/users",
          "1. Open page.",
          "Codes allocated if missing.",
          "allocateHospitalUserIdentity"),
        c("TS-06-023", "Duplicate Mobile", "Create with existing mobile 409", "P0", "Negative",
          "Mobile 9876500011 used.", "SUPER_ADMIN",
          "Same mobile new user",
          "1. Create.",
          "409.",
          "POST /api/hospital/users"),
        c("TS-06-024", "Gender/Employment enums", "Invalid employmentType rejected", "P2", "Negative",
          "—", "SUPER_ADMIN",
          "employmentType: FREELANCER",
          "1. Create.",
          "Ignored/null or validation error — only FULL_TIME PART_TIME CONTRACT CONSULTANT TEMPORARY INTERN.",
          "POST /api/hospital/users"),
        c("TS-06-025", "Department", "departmentId must belong to hospital", "P1", "Negative",
          "Foreign department id.", "SUPER_ADMIN",
          "Wrong hospital departmentId",
          "1. Create doctor with foreign dept.",
          "Rejected / not linked.",
          "POST /api/hospital/users"),
        c("TS-06-026", "Reactivate", "Reactivate user allows login again", "P0", "Positive",
          "Deactivated receptionist.", "SUPER_ADMIN",
          "isActive true",
          "1. Reactivate.\n2. Login.",
          "Login succeeds.",
          "PATCH + login"),
        c("TS-06-027", "Doctor Fees", "Zero consultation fee allowed (falls back later in OPD)", "P2", "Positive",
          "—", "SUPER_ADMIN",
          "consultationFee: 0",
          "1. Save doctor.",
          "Stored. OPD fee chain falls through to hospital/dept/default 500 later (TS-10/14).",
          "PATCH users"),
        c("TS-06-028", "List", "Users list shows seat usage", "P1", "Positive",
          "Several staff.", "SUPER_ADMIN",
          "/hospital/users",
          "1. View seat meter.",
          "Shows used vs limit (SUPER_ADMIN excluded from count).",
          "/hospital/users"),
        c("TS-06-029", "HELPDESK", "Cannot edit HELPDESK via hospital users API", "P1", "RBAC",
          "HELPDESK user id.", "SUPER_ADMIN",
          "PATCH helpdesk user",
          "1. Attempt.",
          "Blocked — platform accounts not editable here.",
          "PATCH /api/hospital/users/[id]"),
        c("TS-06-030", "Photo", "Optional user photo upload/sanitize", "P2", "Positive",
          "Valid small JPEG data-url.", "SUPER_ADMIN",
          "photoData",
          "1. Save with photo.",
          "Stored if valid image type/size.",
          "PATCH users"),
        c("TS-06-031", "Merge note", "User merge covered in TS-05-008 — reference only", "P2", "Positive",
          "—", "SOFTWARE_ADMIN",
          "—",
          "1. Confirm link to TS-05-008.",
          "Staff user merge is platform-only; mark Pass if TS-05-008 passed.",
          "TS-05-008"),
        c("TS-06-032", "Last name optional", "Create user with empty last name", "P1", "Positive",
          "—", "SUPER_ADMIN",
          "firstName only",
          "1. Create.",
          "Allowed (lastName '').",
          "POST /api/hospital/users"),
        c("TS-06-033", "isVerified toggle", "Unverify user blocks login until re-verify", "P1", "Positive",
          "Staff user.", "SUPER_ADMIN",
          "isVerified false",
          "1. Unverify.\n2. Login as that user.",
          "403 needsOtp / not verified.",
          "PATCH + login"),
        c("TS-06-034", "Audit", "USER_CREATED / USER_UPDATED appear in hospital audit log", "P1", "Positive",
          "After create/update.", "SUPER_ADMIN",
          "/hospital/audit-log",
          "1. Filter/search actions.",
          "Entries present with actor + entity AppUser.",
          "GET audit-log"),
        c("TS-06-035", "Roles", "Receptionist and Nurse both remain selectable", "P0", "Positive",
          "SUPER_ADMIN on /hospital/users.", "SUPER_ADMIN",
          "Roles: Receptionist, Nurse",
          "1. Open Add hospital user.\n2. Open Role dropdown.",
          "Receptionist and Nurse are both listed. Helper text: keep a dedicated receptionist, or turn on Nurses as receptionists in Hospital settings. Multiple nurses can share front-desk work.",
          "/hospital/users"),
        c("TS-06-036", "Roles", "Create a second NURSE (multiple nurses allowed)", "P0", "Positive",
          "Seats available. U-H1-NUR exists.", "SUPER_ADMIN",
          "U-H1-NUR2 mobile 9876500016 password Nurse2@123",
          "1. Create another NURSE user.",
          "Second nurse created. Both nurses keep role NURSE (not converted to RECEPTIONIST). Front desk for both depends on the hospital toggle (TS-07-030).",
          "POST /api/hospital/users"),
    ]


def ts07_cases():
    return [
        c("TS-07-001", "Access", "Only SUPER_ADMIN opens /hospital/settings", "P0", "RBAC",
          "—", "RECEPTIONIST",
          "/hospital/settings",
          "1. Open.",
          "Denied/redirect.",
          "/hospital/settings"),
        c("TS-07-002", "Branding", "Update address, phone, opdFee, logo, seal", "P0", "Positive",
          "SUPER_ADMIN.", "SUPER_ADMIN",
          "address: new\nphone: 9876500001\nopdFee: 400\nlogo/seal valid images",
          "1. Save branding.",
          "Persisted. Audit HOSPITAL_BRANDING_UPDATED. PDFs later use logo/seal (spot-check in TS-12/14).",
          "PATCH /api/hospital/settings"),
        c("TS-07-003", "opdFee", "Negative opdFee rejected", "P1", "Boundary",
          "—", "SUPER_ADMIN",
          "opdFee: -1",
          "1. Save.",
          "Rejected.",
          "PATCH /api/hospital/settings"),
        c("TS-07-004", "Signature Policy", "Enable requireSignatureForApproval", "P0", "Positive",
          "Doctors have ACTIVE signatures (or accept warning).", "SUPER_ADMIN",
          "requireSignatureForApproval: true",
          "1. Enable policy.",
          "Saved. Audit HOSPITAL_SIGNATURE_POLICY_UPDATED. UI may warn if doctors lack signatures.",
          "PATCH /api/hospital/settings"),
        c("TS-07-005", "Signature Policy", "Approve visit blocked without signature when required", "P0", "Negative",
          "Policy ON. Doctor without ACTIVE signature. Visit with diagnosis.", "DOCTOR",
          "action approve assessment",
          "1. Approve visit summary.",
          "Blocked — active signature required. (Full clinical steps in TS-12; this checks settings effect.)",
          "POST .../assessment"),
        c("TS-07-006", "Walk-in Policy", "walkInByDoctor default true — doctor can walk-in", "P0", "Positive",
          "walkInByDoctor true (default).", "DOCTOR",
          "—",
          "1. Open new appointment as doctor.",
          "Can create WALK_IN (auto self-assigned). Detail in TS-10.",
          "canAddWalkIn"),
        c("TS-07-007", "Walk-in Policy", "Disable walkInByDoctor — doctor cannot walk-in", "P0", "Positive",
          "Set walkInByDoctor false.", "DOCTOR",
          "—",
          "1. Attempt walk-in create.",
          "Denied. Audit HOSPITAL_WALK_IN_POLICY_UPDATED when setting changed.",
          "PATCH settings + appointments"),
        c("TS-07-008", "Walk-in Policy", "Enable walkInByNurse — nurse can walk-in (narrow toggle)", "P1", "Positive",
          "walkInByNurse true. nurseAsReceptionist false.", "NURSE",
          "—",
          "1. Create walk-in.",
          "Allowed. Nurse still cannot open billing / edit patient demographics (that needs Nurses as receptionists).",
          "PATCH settings + appointments"),
        c("TS-07-009", "Admin Doctor", "Enable admin-as-doctor create mode requires specialization + reg no", "P0", "Negative",
          "SUPER_ADMIN without doctor staff.", "SUPER_ADMIN",
          "enabled create without specialization",
          "1. Submit doctor profile.",
          "400 specialization + medicalRegNo required.",
          "PUT /api/hospital/doctor-profile"),
        c("TS-07-010", "Admin Doctor", "Create admin-as-doctor profile succeeds", "P0", "Positive",
          "Valid specialization + reg.", "SUPER_ADMIN",
          "mode create\nspecialization: General Medicine\nmedicalRegNo: KMC-999",
          "1. Enable admin doctor.",
          "Staff DOCTOR linked. Audit ADMIN_DOCTOR_ENABLED. View-mode available.",
          "PUT /api/hospital/doctor-profile"),
        c("TS-07-011", "Admin Doctor", "Link mode to existing doctor staff", "P1", "Positive",
          "Existing doctor Staff not linked elsewhere.", "SUPER_ADMIN",
          "mode=link staffId=...",
          "1. Link.",
          "Linked. Audit ADMIN_DOCTOR_LINKED. Conflict 409 if already linked to another admin.",
          "PUT /api/hospital/doctor-profile"),
        c("TS-07-012", "Admin Doctor", "Disable admin-as-doctor", "P1", "Positive",
          "Admin doctor enabled.", "SUPER_ADMIN",
          "enabled=false",
          "1. Disable.",
          "Linked Staff isActive false. Audit ADMIN_DOCTOR_DISABLED. Doctor view-mode unavailable.",
          "PUT /api/hospital/doctor-profile"),
        c("TS-07-013", "View Mode", "Eligible SUPER_ADMIN toggles admin|doctor", "P0", "Positive",
          "Admin-as-doctor active.", "SUPER_ADMIN",
          "mode: doctor then admin",
          "1. Toggle via UI / POST view-mode.",
          "Cookie mederp_view_mode set. Nav switches doctorNav vs superAdminNav. Default doctor if eligible.",
          "POST /api/session/view-mode"),
        c("TS-07-014", "View Mode", "Doctor mode forbidden without doctor staff profile", "P0", "Negative",
          "SUPER_ADMIN without doctor staff.", "SUPER_ADMIN",
          "mode: doctor",
          "1. POST view-mode doctor.",
          "403.",
          "POST /api/session/view-mode"),
        c("TS-07-015", "Redirect", "/hospital/settings/doctor-profile redirects to settings", "P2", "Positive",
          "—", "SUPER_ADMIN",
          "/hospital/settings/doctor-profile",
          "1. Open.",
          "Redirect to /hospital/settings.",
          "doctor-profile/page.tsx"),
        c("TS-07-016", "Logo size", "Oversized logo rejected", "P2", "Boundary",
          "—", "SUPER_ADMIN",
          "Huge base64 image",
          "1. Save.",
          "Sanitize rejects.",
          "PATCH /api/hospital/settings"),
        c("TS-07-017", "opdFee Effect", "Hospital opdFee used when doctor fee unset", "P1", "Positive",
          "Doctor consultationFee 0/null. Hospital opdFee 400.", "RECEPTIONIST",
          "Collect OPD for that doctor",
          "1. Create visit + open collect (detail TS-14).",
          "Fee shows ₹400 from hospital.",
          "consultationFeeForVisit"),
        c("TS-07-018", "Audit", "Settings changes appear in audit log", "P1", "Positive",
          "After branding/policy/follow-up reminder updates.", "SUPER_ADMIN",
          "/hospital/audit-log",
          "1. Verify HOSPITAL_*_UPDATED actions.",
          "Present with field diffs (images redacted). Includes HOSPITAL_FOLLOW_UP_REMINDER_POLICY_UPDATED after TS-07-036.",
          "audit-log"),
        c("TS-07-019", "Doctor Hours", "Settings shows Doctor availability hours section", "P0", "Positive",
          "At least one active DOCTOR staff.", "SUPER_ADMIN",
          "/hospital/settings",
          "1. Scroll to Doctor availability hours.\n2. Confirm each active doctor has an editor.\n3. Open day dropdown.",
          "Section visible. Day options include Everyday, Weekdays, Weekend, and each single day.",
          "/hospital/settings"),
        c("TS-07-020", "Doctor Hours", "Save multiple windows same day (morning/afternoon/evening)", "P0", "Positive",
          "Active doctor D1.", "SUPER_ADMIN",
          "Mon 10:00–12:00, 14:00–16:00, 18:00–20:00",
          "1. Add three Monday windows.\n2. Save availability.",
          "Saved. Audit DOCTOR_AVAILABILITY_UPDATED. GET returns 3 windows.",
          "PUT /api/hospital/staff/[id]/availability"),
        c("TS-07-021", "Doctor Hours", "Overlapping windows on same day rejected", "P0", "Negative",
          "Doctor D1.", "SUPER_ADMIN",
          "Mon 10:00–13:00 and 12:00–14:00",
          "1. Save overlapping windows.",
          "400 with overlap error. Previous windows unchanged.",
          "PUT availability"),
        c("TS-07-022", "Doctor Hours", "End time must be after start time", "P1", "Negative",
          "Doctor D1.", "SUPER_ADMIN",
          "Tue start 16:00 end 10:00",
          "1. Save.",
          "400 End time must be after start time.",
          "PUT availability"),
        c("TS-07-023", "Doctor Hours", "Weekdays preset expands to Mon–Fri", "P0", "Positive",
          "Active doctor D1.", "SUPER_ADMIN",
          "Day = Weekdays (Mon–Fri), 10:00–13:00",
          "1. Add window → Weekdays → 10:00–13:00.\n2. Save.\n3. GET availability.",
          "Saved as 5 windows (Mon–Fri same band). Reload shows Weekdays row collapsed.",
          "PUT/GET /api/hospital/staff/[id]/availability"),
        c("TS-07-024", "Doctor Hours", "Weekend preset expands to Sat–Sun", "P0", "Positive",
          "Active doctor D1.", "SUPER_ADMIN",
          "Day = Weekend (Sat–Sun), 10:00–12:00",
          "1. Add Weekend window 10:00–12:00.\n2. Save.\n3. GET.",
          "2 windows (Saturday + Sunday). Reload shows Weekend row.",
          "PUT/GET availability"),
        c("TS-07-025", "Doctor Hours", "Everyday preset expands to all 7 days", "P0", "Positive",
          "Active doctor D1.", "SUPER_ADMIN",
          "Day = Everyday (Sun–Sat), 09:00–17:00",
          "1. Add Everyday window.\n2. Save.\n3. GET.",
          "7 windows (Sun–Sat). Reload collapses to Everyday row.",
          "PUT/GET availability"),
        c("TS-07-026", "Doctor Hours", "Different doctors have independent schedules", "P0", "Positive",
          "Active doctors D1 and D2.", "SUPER_ADMIN",
          "D1 Weekdays 10–13; D2 Weekend 10–12",
          "1. Save D1 Weekdays 10:00–13:00.\n2. Save D2 Weekend 10:00–12:00.\n3. GET both.",
          "D1 has Mon–Fri only. D2 has Sat–Sun only. No cross-contamination.",
          "PUT/GET availability per staff id"),
        c("TS-07-027", "Nurse Receptionist", "Toggle default OFF — nurses stay off the front desk", "P0", "RBAC",
          "H1. U-H1-NUR exists. nurseAsReceptionist never enabled (default false).", "NURSE",
          "/patients/new, /billing, queue manage",
          "1. Login as nurse.\n2. Open /patients/new, /billing, try cancel/reschedule a visit.",
          "Register/edit patient denied. Billing redirected/denied. Queue manage actions denied. Nurse station still available.",
          "hasFrontDeskAccess / hasBillingAccess"),
        c("TS-07-028", "Nurse Receptionist", "SUPER_ADMIN enables Nurses as receptionists", "P0", "Positive",
          "Logged in as U-H1-SUPER.", "SUPER_ADMIN",
          "nurseAsReceptionist: true",
          "1. Open /hospital/settings.\n2. Tick Nurses can do receptionist work.\n3. Save nurse reception access.",
          "PATCH 200. Audit HOSPITAL_NURSE_RECEPTIONIST_POLICY_UPDATED. Dedicated Receptionist role is still available on Hospital users.",
          "PATCH /api/hospital/settings"),
        c("TS-07-029", "Nurse Receptionist", "Non-admin cannot change the nurse receptionist toggle", "P0", "RBAC",
          "Toggle currently true or false.", "RECEPTIONIST / NURSE",
          "PATCH nurseAsReceptionist",
          "1. Call PATCH /api/hospital/settings with nurseAsReceptionist.",
          "403 Hospital admin access required. Flag unchanged.",
          "PATCH /api/hospital/settings"),
        c("TS-07-030", "Nurse Receptionist", "Toggle ON — every nurse gets front desk; receptionist still works", "P0", "Positive",
          "nurseAsReceptionist true. U-H1-NUR, U-H1-NUR2, U-H1-REC exist.", "NURSE / RECEPTIONIST",
          "—",
          "1. Login as U-H1-NUR: register patient, add walk-in, open /billing.\n2. Repeat as U-H1-NUR2.\n3. Login as U-H1-REC: same front-desk actions still work.",
          "Both nurses can register, walk-in, collect. Receptionist unchanged. Nav for nurses includes Billing plus Nurse station.",
          "hasFrontDeskAccess + nav"),
        c("TS-07-031", "Nurse Receptionist", "Toggle ON implies walk-in even if walkInByNurse is off", "P0", "Positive",
          "nurseAsReceptionist true. walkInByNurse false.", "NURSE",
          "WALK_IN",
          "1. Confirm walk-in-by-nurse checkbox is disabled/checked in settings.\n2. Nurse creates walk-in.",
          "Walk-in allowed. Settings copy explains nurses already cover reception.",
          "canAddWalkIn"),
        c("TS-07-032", "Nurse Receptionist", "Toggle OFF restores nurse-only (does not remove Receptionist users)", "P0", "Positive",
          "Toggle was ON. U-H1-REC still exists.", "SUPER_ADMIN → NURSE / RECEPTIONIST",
          "nurseAsReceptionist: false",
          "1. Superadmin unchecks and saves.\n2. Login nurse — retry register/billing.\n3. Login receptionist — retry billing.",
          "Audit HOSPITAL_NURSE_RECEPTIONIST_POLICY_UPDATED. Nurse denied front desk again. Receptionist still has full front desk. Nurse user rows unchanged.",
          "PATCH /api/hospital/settings"),
        c("TS-07-033", "Nurse Receptionist", "Empty PATCH / missing field rejected; branding still independent", "P2", "Negative",
          "SUPER_ADMIN.", "SUPER_ADMIN",
          "body {}",
          "1. PATCH settings with empty body.",
          "400 Nothing to update. Existing nurseAsReceptionist unchanged.",
          "PATCH /api/hospital/settings"),
        c("TS-07-034", "Nurse Receptionist", "Only one SUPER_ADMIN; admin-as-doctor remains that one admin", "P1", "Positive",
          "H1 has one SUPER_ADMIN. Toggle on or off.", "SUPER_ADMIN",
          "Hospital users + settings",
          "1. Confirm hospital UI cannot create a second SUPER_ADMIN.\n2. Confirm admin-as-doctor still uses the same admin (TS-07-010).",
          "Staff roles only (including Receptionist and multiple Nurses). One hospital admin. Unrelated to nurse receptionist toggle.",
          "TS-06-009 + doctor-profile"),
        c("TS-07-035", "Follow-up Reminder", "Settings shows Follow-up reminders section off by default", "P0", "Positive",
          "New/default hospital. SUPER_ADMIN.", "SUPER_ADMIN",
          "/hospital/settings",
          "1. Scroll to Follow-up reminders.\n2. Confirm checkbox and 1/2 day radios.",
          "Section visible. 'Send follow-up reminders automatically' unchecked. Default lead time 1 day before (~09:00). Radios disabled until enabled. Reception can still send a manual reminder from the visit.",
          "/hospital/settings"),
        c("TS-07-036", "Follow-up Reminder", "Enable auto reminder + 1 day before", "P0", "Positive",
          "SUPER_ADMIN on settings.", "SUPER_ADMIN",
          "followUpReminderEnabled true\nfollowUpReminderDaysBefore 1",
          "1. Tick Send follow-up reminders automatically.\n2. Leave 1 day before selected.\n3. Save follow-up reminders.",
          "Saved. UI shows success. Audit HOSPITAL_FOLLOW_UP_REMINDER_POLICY_UPDATED. Visit assessment shows hint: Patients get a WhatsApp reminder 1 day before the follow-up.",
          "PATCH /api/hospital/settings"),
        c("TS-07-037", "Follow-up Reminder", "Switch lead time to 2 days before", "P0", "Positive",
          "After TS-07-036.", "SUPER_ADMIN",
          "followUpReminderDaysBefore 2",
          "1. Select 2 days before.\n2. Save.",
          "Saved. Hint becomes 2 days before. Invalid values (0, 3, string) coerce to 1 via API.",
          "PATCH /api/hospital/settings"),
        c("TS-07-038", "Follow-up Reminder", "Disable cancels pending FOLLOW_UP reminders hospital-wide", "P0", "Positive",
          "Policy ON. At least one PENDING AppointmentReminder source=FOLLOW_UP exists (TS-12).", "SUPER_ADMIN",
          "followUpReminderEnabled false",
          "1. Untick Send follow-up reminders automatically.\n2. Save.",
          "Setting false. All PENDING FOLLOW_UP reminders for this hospital become CANCELLED. MANUAL reminders unchanged. Audit HOSPITAL_FOLLOW_UP_REMINDER_POLICY_UPDATED.",
          "PATCH /api/hospital/settings"),
        c("TS-07-039", "Follow-up Reminder", "Empty PATCH still rejected; follow-up fields count as an update", "P1", "Negative",
          "SUPER_ADMIN.", "SUPER_ADMIN",
          "body {} vs body {followUpReminderEnabled:true}",
          "1. PATCH settings with empty body.\n2. PATCH with only follow-up fields.",
          "Empty 400 Nothing to update. Follow-up-only body succeeds (does not require branding).",
          "PATCH /api/hospital/settings"),
        c("TS-07-040", "Follow-up Reminder", "Only SUPER_ADMIN can change follow-up reminder policy", "P0", "RBAC",
          "Policy currently off.", "RECEPTIONIST / DOCTOR / NURSE",
          "PATCH followUpReminderEnabled true",
          "1. Attempt PATCH /api/hospital/settings as each role.",
          "403. Receptionist can still send a manual visit reminder (TS-10-025).",
          "PATCH /api/hospital/settings"),
        c("TS-07-041", "Follow-up Reminder", "Lead-time radios only apply when auto-send is on", "P1", "Positive",
          "SUPER_ADMIN on settings.", "SUPER_ADMIN",
          "/hospital/settings",
          "1. Leave auto-send off; try clicking 2 days before.\n2. Enable auto-send; radios become active.",
          "Radios disabled while off. Enabling does not send reminders until a follow-up is saved (TS-12).",
          "/hospital/settings"),
    ]


def ts08_cases():
    return [
        c("TS-08-001", "Apply", "Staff can apply leave (PENDING)", "P0", "Positive",
          "DOCTOR logged in. No overlap.", "DOCTOR",
          "type: SICK\nstart/end: tomorrow → +2 days\nreason: Fever",
          "1. /leave → Apply.",
          "Status PENDING. SUPER_ADMIN notified. Audit STAFF_LEAVE_APPLIED. Blocks booking for those days.",
          "POST /api/leaves"),
        c("TS-08-002", "Types", "Leave types CASUAL SICK EARNED EMERGENCY OTHER", "P1", "Positive",
          "—", "NURSE",
          "Each type once (non-overlapping dates)",
          "1. Apply each.",
          "All accepted. Invalid type coerced to CASUAL.",
          "POST /api/leaves"),
        c("TS-08-003", "Overlap", "Overlapping PENDING/APPROVED leave rejected", "P0", "Negative",
          "PENDING leave exists for doctor dates.", "DOCTOR",
          "Overlapping range",
          "1. Apply again.",
          "409 overlap.",
          "POST /api/leaves"),
        c("TS-08-004", "Dates", "endAt must be after startAt", "P1", "Boundary",
          "—", "DOCTOR",
          "end before start",
          "1. Apply.",
          "400 validation.",
          "POST /api/leaves"),
        c("TS-08-005", "Approve", "Only SUPER_ADMIN approves", "P0", "RBAC",
          "PENDING leave.", "RECEPTIONIST / DOCTOR",
          "action approve",
          "1. Attempt approve.",
          "403. Only SUPER_ADMIN.",
          "PATCH /api/leaves/[id]"),
        c("TS-08-006", "Approve", "SUPER_ADMIN approve → APPROVED + notify applicant", "P0", "Positive",
          "PENDING leave. /hospital/leaves.", "SUPER_ADMIN",
          "approve",
          "1. Approve.",
          "APPROVED. Applicant notified. Audit STAFF_LEAVE_APPROVE.",
          "PATCH /api/leaves/[id]"),
        c("TS-08-007", "Reject", "Reject → REJECTED; no longer blocks booking", "P0", "Positive",
          "Another PENDING leave.", "SUPER_ADMIN",
          "reject + reviewNote",
          "1. Reject.\n2. Book appointment on those dates.",
          "REJECTED. Booking allowed (rejected does not block).",
          "PATCH leaves + appointments"),
        c("TS-08-008", "Cancel Own", "Applicant cancels own PENDING", "P1", "Positive",
          "Own PENDING leave.", "DOCTOR",
          "cancel",
          "1. Cancel.",
          "CANCELLED. No longer blocks.",
          "PATCH /api/leaves/[id]"),
        c("TS-08-009", "Cancel Admin", "SUPER_ADMIN can cancel APPROVED leave", "P1", "Positive",
          "APPROVED leave.", "SUPER_ADMIN",
          "cancel",
          "1. Cancel.",
          "CANCELLED. Booking unblocked.",
          "PATCH /api/leaves/[id]"),
        c("TS-08-010", "Cancel Own Approved", "Applicant cannot cancel APPROVED", "P1", "Negative",
          "APPROVED leave owned by doctor.", "DOCTOR",
          "cancel",
          "1. Attempt.",
          "Denied — only SUPER_ADMIN cancels approved.",
          "PATCH /api/leaves/[id]"),
        c("TS-08-011", "Record", "SUPER_ADMIN/RECEPTIONIST can record pre-approved leave", "P0", "Positive",
          "No overlap with APPROVED.", "RECEPTIONIST",
          "record=true type CASUAL dates",
          "1. Record leave.",
          "Created APPROVED (or recorded path). Audit STAFF_LEAVE_RECORDED. Blocks booking.",
          "POST /api/leaves"),
        c("TS-08-012", "Blocking", "PENDING leave blocks doctor appointment create", "P0", "Negative",
          "Doctor has PENDING leave tomorrow.", "RECEPTIONIST",
          "scheduledAt on leave day",
          "1. Book appointment for that doctor.",
          "409 doctor on leave.",
          "POST /api/appointments"),
        c("TS-08-013", "Blocking", "APPROVED leave blocks booking", "P0", "Negative",
          "APPROVED leave day.", "RECEPTIONIST",
          "same",
          "1. Book.",
          "409 on leave.",
          "POST /api/appointments"),
        c("TS-08-014", "leaveAt API", "GET appointments?leaveAt returns onLeaveDoctorIds", "P1", "Positive",
          "Doctor on leave that date.", "RECEPTIONIST",
          "leaveAt=YYYY-MM-DD",
          "1. Call API / open appointment form.",
          "Doctor id listed. UI blocks submit for that doctor.",
          "GET /api/appointments?leaveAt="),
        c("TS-08-015", "SUPER_ADMIN Apply", "SUPER_ADMIN cannot apply leave via canApplyLeave", "P2", "RBAC",
          "—", "SUPER_ADMIN",
          "POST leave as self",
          "1. Apply.",
          "Blocked — STAFF_ROLES only (SUPER_ADMIN excluded from apply).",
          "POST /api/leaves"),
        c("TS-08-016", "List", "Hospital leaves page for SUPER_ADMIN; /leave for staff", "P1", "Positive",
          "—", "SUPER_ADMIN / DOCTOR",
          "/hospital/leaves and /leave",
          "1. Open each.",
          "Admin sees all hospital leaves; staff sees own + apply form.",
          "pages"),
        c("TS-08-017", "Terminal", "Cannot approve already REJECTED leave", "P2", "Negative",
          "REJECTED leave.", "SUPER_ADMIN",
          "approve",
          "1. Attempt.",
          "409 / invalid transition.",
          "PATCH /api/leaves/[id]"),
        c("TS-08-018", "Same Day", "Leave covering today blocks today's walk-in for that doctor", "P1", "Negative",
          "APPROVED leave includes today.", "RECEPTIONIST",
          "Walk-in now for that doctor",
          "1. Create walk-in.",
          "409 on leave.",
          "POST /api/appointments"),
        c("TS-08-019", "Staff Ensure", "First leave for joined non-doctor may create Staff lazily", "P2", "Positive",
          "Joined RECEPTIONIST without Staff row if applicable.", "RECEPTIONIST",
          "Apply leave",
          "1. Apply.",
          "Leave created; Staff ensured if coded path runs.",
          "ensureStaffForUser"),
        c("TS-08-020", "Audit", "Leave actions in audit log", "P2", "Positive",
          "After apply/approve.", "SUPER_ADMIN",
          "STAFF_LEAVE_*",
          "1. Check audit.",
          "Actions present.",
          "audit-log"),
        c("TS-08-021", "Record RBAC", "Nurse cannot record leave when receptionist toggle is off", "P1", "RBAC",
          "nurseAsReceptionist false.", "NURSE",
          "record=true",
          "1. POST /api/leaves with record=true.",
          "403 Only reception or super admin can record leave directly.",
          "POST /api/leaves"),
        c("TS-08-022", "Record RBAC", "Nurse can record leave when Nurses as receptionists is on", "P1", "Positive",
          "nurseAsReceptionist true (TS-07-028). No overlap.", "NURSE",
          "record=true type CASUAL dates",
          "1. Record leave for a doctor from appointments leave form or API.",
          "Created APPROVED. Same as receptionist record path.",
          "POST /api/leaves"),
    ]
