"""TS-14 through TS-20 manual cases."""
from case_util import c


def ts14_cases():
    return [
        c("TS-14-001", "Access", "BILLING_ROLES can open /billing", "P0", "RBAC",
          "nurseAsReceptionist false (default).", "RECEPTIONIST / ACCOUNTANT / DOCTOR / NURSE",
          "/billing",
          "1. Open as each.",
          "Receptionist, accountant, doctor ok. Nurse redirected/denied (see TS-14-029 when toggle on).",
          "/billing"),
        c("TS-14-002", "OPD Collect", "Full CASH collect creates PAID invoice", "P0", "Positive",
          "Walk-in unpaid today. Fee known.", "RECEPTIONIST",
          "method CASH amount=due exact",
          "1. /billing/collect/[appointmentId] → pay.",
          "Invoice INV-{CODE}-NNNNN created if none. status PAID. Payment COLLECTION. paidAmount=netTotal.",
          "POST /api/appointments/[id]/collect"),
        c("TS-14-003", "OPD Partial", "Partial amount rejected on collect", "P0", "Negative",
          "Unpaid visit.", "RECEPTIONIST",
          "amount < due",
          "1. Pay partial.",
          "400 full amount required (±0.01).",
          "POST collect"),
        c("TS-14-004", "OPD Overpay", "Overpay rejected", "P0", "Negative",
          "—", "RECEPTIONIST",
          "amount > due + 0.01",
          "1. Pay.",
          "400 more than balance due.",
          "POST collect"),
        c("TS-14-005", "Card", "CARD requires brand; last4 optional 4 digits", "P0", "Positive",
          "Unpaid visit.", "RECEPTIONIST",
          "CARD Visa last4 1234",
          "1. Pay with brand.\n2. Pay CARD without brand.",
          "With brand ok. Without brand 400 choose card type. Brands: Visa Mastercard RuPay Amex Other.",
          "POST collect"),
        c("TS-14-006", "UPI", "UPI full payment succeeds", "P1", "Positive",
          "Unpaid.", "RECEPTIONIST",
          "UPI exact due",
          "1. Pay.",
          "PAID.",
          "POST collect"),
        c("TS-14-007", "Already Paid", "Second collect 409", "P0", "Negative",
          "Already PAID visit invoice.", "RECEPTIONIST",
          "collect again",
          "1. Pay.",
          "409 already paid.",
          "POST collect"),
        c("TS-14-008", "Cancel Block", "Collect blocked for CANCELLED/NO_SHOW", "P0", "Negative",
          "NO_SHOW.", "RECEPTIONIST",
          "—",
          "1. Collect.",
          "409.",
          "POST collect"),
        c("TS-14-009", "Manual Invoice", "Create standalone invoice with line items", "P0", "Positive",
          "Patient P5.", "RECEPTIONIST",
          "items: Consult 500, Procedure 200\ndiscount 0",
          "1. /billing/new → save.",
          "subtotal=700 status ISSUED invoiceNo unique. Items with amount>0 only.",
          "POST /api/invoices"),
        c("TS-14-010", "Line Filter", "Empty description / zero amount lines dropped", "P1", "Positive",
          "—", "RECEPTIONIST",
          "item blank / amount 0 + valid item",
          "1. Create.",
          "Only valid lines in subtotal.",
          "POST invoices"),
        c("TS-14-011", "100% Discount Create", "netTotal 0 → status PAID at create", "P0", "Positive",
          "—", "RECEPTIONIST",
          "item 500 discount 500",
          "1. Create.",
          "netTotal 0 status PAID.",
          "POST invoices"),
        c("TS-14-012", "Discount Cap", "discount > subtotal rejected", "P0", "Negative",
          "—", "RECEPTIONIST",
          "subtotal 100 discount 150",
          "1. Create/pay discount.",
          "400.",
          "create / discount"),
        c("TS-14-013", "Appt Linked Create", "Invoice from appointment uses doctor/dept fee (not followUp helper)", "P1", "Positive",
          "FOLLOW_UP visit. followUpFee 200 consultationFee 500.", "RECEPTIONIST",
          "/billing/new with appointment vs /collect",
          "1. Compare amounts.",
          "Document W-07: new may use consultationFee; collect uses consultationFeeForVisit.",
          "POST invoices vs collect"),
        c("TS-14-014", "Partial Pay Standalone", "Partial pay → PARTIALLY_PAID", "P0", "Positive",
          "ISSUED standalone no appointment.", "RECEPTIONIST",
          "pay half (requireFull false)",
          "1. PATCH pay.",
          "PARTIALLY_PAID. paidAmount updated.",
          "PATCH /api/invoices/[id] pay"),
        c("TS-14-015", "Partial Appt Invoice", "Partial on appointment-linked invoice rejected by API", "P0", "Negative",
          "ISSUED with appointmentId.", "RECEPTIONIST",
          "partial pay",
          "1. PATCH pay partial.",
          "400 full required.",
          "PATCH pay"),
        c("TS-14-016", "Full Pay", "Exact remaining → PAID (tol 0.001)", "P0", "Positive",
          "PARTIALLY_PAID standalone.", "ACCOUNTANT",
          "pay remaining",
          "1. Pay.",
          "PAID.",
          "PATCH pay"),
        c("TS-14-017", "Methods", "Invoice pay allows CASH CARD UPI INSURANCE ADVANCE", "P1", "Positive",
          "Standalone due.", "RECEPTIONIST",
          "Each method once across invoices",
          "1. Pay with each.",
          "All accepted when rules met (ADVANCE needs balance — TS-15).",
          "PATCH pay"),
        c("TS-14-018", "List Search", "Search invoices by no, name, MRN", "P1", "Positive",
          "Invoices exist.", "RECEPTIONIST",
          "q=INV / patient name",
          "1. Search list/API.",
          "Matches ≤80.",
          "GET /api/invoices?q="),
        c("TS-14-019", "Detail", "Invoice detail shows items payments totals", "P0", "Positive",
          "Paid invoice.", "RECEPTIONIST",
          "/billing/[id]",
          "1. Open.",
          "Subtotal discount waiver net paid due + payments list.",
          "detail page"),
        c("TS-14-020", "No Tax", "No GST fields on hospital invoice", "P2", "Positive",
          "—", "RECEPTIONIST",
          "Create invoice",
          "1. Inspect model/UI.",
          "Only flat amount lines — no tax. Pass if confirmed.",
          "schema/UI"),
        c("TS-14-021", "Numbering", "Sequential invoice numbers per hospital", "P0", "Positive",
          "Create two invoices.", "RECEPTIONIST",
          "—",
          "1. Create two.",
          "Numbers increment INV-{CODE}-0000N unique per hospital.",
          "POST invoices"),
        c("TS-14-022", "RBAC Nurse", "Nurse cannot PATCH pay when receptionist toggle is off", "P0", "RBAC",
          "ISSUED invoice. nurseAsReceptionist false.", "NURSE",
          "pay",
          "1. PATCH.",
          "403.",
          "PATCH pay"),
        c("TS-14-023", "Doctor Billing", "Doctor in BILLING_ROLES can collect", "P1", "Positive",
          "Unpaid visit.", "DOCTOR",
          "CASH full",
          "1. Collect.",
          "Allowed.",
          "POST collect"),
        c("TS-14-024", "Float Tol", "Pay amounts 33.33 / 66.67 within ±0.01", "P1", "Boundary",
          "Invoice net 100.", "RECEPTIONIST",
          "partial 33.33 then 66.67 if standalone",
          "1. Two payments.",
          "Ends PAID without float error.",
          "PATCH pay"),
        c("TS-14-025", "VOID DRAFT", "Confirm no UI to void/draft (W-05)", "P1", "Positive",
          "—", "RECEPTIONIST",
          "Invoice detail actions",
          "1. Look for void/draft.",
          "Not available. Document W-05 Pass as observation.",
          "UI"),
        c("TS-14-026", "Tenant", "Cannot pay other hospital invoice", "P0", "Security",
          "H4 invoice id.", "RECEPTIONIST H1",
          "—",
          "1. PATCH pay.",
          "404/403.",
          "PATCH"),
        c("TS-14-027", "Zero Item", "Create with no valid items fails or zero handling", "P1", "Negative",
          "—", "RECEPTIONIST",
          "no items",
          "1. Create.",
          "Rejected or explicit error — document actual.",
          "POST invoices"),
        c("TS-14-028", "Receipt Preview", "Print receipt shows hospital patient lines payments", "P0", "Positive",
          "PAID invoice.", "RECEPTIONIST",
          "Print on detail",
          "1. Print/PDF.",
          "%PDF; invoiceNo; totals; payments; received by if signature.",
          "bill-receipt-pdf"),
        c("TS-14-029", "Nurse Receptionist On", "Nurse can collect OPD and open invoices when toggle is on", "P0", "Positive",
          "nurseAsReceptionist true. Unpaid walk-in. Refresh nurse session.", "NURSE",
          "CASH amount=due",
          "1. Open /billing.\n2. Collect on /billing/collect/[id].",
          "Billing pages load. Collect succeeds. Invoice PAID. Nurse still cannot approve waivers (TS-15) — only request if UI shows request.",
          "POST collect + /billing"),
        c("TS-14-030", "Nurse Receptionist On", "Nurse cannot approve waiver even with front-desk access", "P0", "RBAC",
          "Toggle ON. PENDING waiver.", "NURSE",
          "waiver-decide",
          "1. Try approve/reject waiver.",
          "403 — WAIVER_APPROVER_ROLES remain SUPER_ADMIN + ACCOUNTANT only.",
          "PATCH waiver-decide"),
    ]


def ts15_cases():
    return [
        c("TS-15-001", "Discount", "Apply discount reduces netTotal", "P0", "Positive",
          "ISSUED unpaid subtotal 1000.", "RECEPTIONIST",
          "discount 100",
          "1. Apply discount.",
          "netTotal 900. Status recalculated.",
          "PATCH discount"),
        c("TS-15-002", "Discount Cap", "discount > subtotal 400", "P0", "Negative",
          "subtotal 500", "RECEPTIONIST",
          "discount 600",
          "1. Apply.",
          "400.",
          "PATCH discount"),
        c("TS-15-003", "Discount Paid", "Discount making net < paidAmount → 409", "P0", "Negative",
          "paidAmount 800 net 1000", "RECEPTIONIST",
          "discount 300 → net 700",
          "1. Apply.",
          "409.",
          "PATCH discount"),
        c("TS-15-004", "Discount No Approval", "Discount needs no waiver approver", "P1", "Positive",
          "—", "RECEPTIONIST",
          "discount 50",
          "1. Apply as receptionist.",
          "Succeeds without accountant.",
          "PATCH discount"),
        c("TS-15-005", "Waiver Request", "Front desk requests waiver PENDING", "P0", "Positive",
          "ISSUED invoice.", "RECEPTIONIST",
          "amount 100 reason: Poor patient",
          "1. Request waiver.",
          "waiverStatus PENDING. netTotal UNCHANGED. ACCOUNTANT+SUPER notified. Audit.",
          "PATCH waiver-request"),
        c("TS-15-006", "Waiver Request Val", "amount>0 and reason required", "P0", "Negative",
          "—", "RECEPTIONIST",
          "A) amount 0 B) empty reason",
          "1. Request.",
          "400 both.",
          "PATCH waiver-request"),
        c("TS-15-007", "Waiver RBAC Request", "Doctor cannot request waiver (not FRONT_DESK)", "P1", "RBAC",
          "—", "DOCTOR",
          "waiver-request",
          "1. Request.",
          "403 (FRONT_DESK only).",
          "PATCH"),
        c("TS-15-008", "Waiver Approve", "ACCOUNTANT/SUPER approve reduces net", "P0", "Positive",
          "PENDING waiver 100 on subtotal 1000 discount 0.", "ACCOUNTANT",
          "approve true",
          "1. Approve.",
          "APPROVED. netTotal 900. due reduced. W-06: before approve due was still 1000.",
          "PATCH waiver-decide"),
        c("TS-15-009", "Waiver Reject", "Reject clears waiverAmount", "P0", "Positive",
          "Another PENDING.", "SUPER_ADMIN",
          "approve false",
          "1. Reject.",
          "REJECTED. waiverAmount 0. netTotal = subtotal - discount.",
          "PATCH waiver-decide"),
        c("TS-15-010", "Waiver RBAC Decide", "RECEPTIONIST cannot approve waiver", "P0", "RBAC",
          "PENDING.", "RECEPTIONIST",
          "approve",
          "1. Decide.",
          "403 WAIVER_APPROVER only.",
          "PATCH"),
        c("TS-15-011", "Waiver Not Pending", "Decide when not PENDING → 409", "P1", "Negative",
          "Already APPROVED.", "ACCOUNTANT",
          "decide again",
          "1. Decide.",
          "409.",
          "PATCH"),
        c("TS-15-012", "Waiver After Pay", "Approve blocked if paidAmount > new net", "P0", "Negative",
          "Paid full 1000 then pending waiver 200", "ACCOUNTANT",
          "approve",
          "1. Pay full while PENDING (W-06).\n2. Approve waiver.",
          "409 cannot approve — paid exceeds new net.",
          "PATCH"),
        c("TS-15-013", "Advance Collect", "POST advance increases advanceBalance", "P0", "Positive",
          "Patient P5.", "RECEPTIONIST",
          "amount 500 method CASH",
          "1. /billing/advance → collect.",
          "Payment kind ADVANCE. advanceBalance +=500. Audit ADVANCE_COLLECTED. Methods CASH CARD UPI INSURANCE (not ADVANCE).",
          "POST /api/payments/advance"),
        c("TS-15-014", "Advance Val", "amount must be >0", "P1", "Negative",
          "—", "RECEPTIONIST",
          "amount 0",
          "1. Collect.",
          "400.",
          "POST advance"),
        c("TS-15-015", "Advance Apply", "Pay invoice with method ADVANCE decrements balance", "P0", "Positive",
          "advanceBalance 500. Invoice due 300.", "RECEPTIONIST",
          "method ADVANCE amount 300",
          "1. Pay.",
          "COLLECTION+ADVANCE. balance 200. Invoice paidAmount +300.",
          "PATCH pay"),
        c("TS-15-016", "Advance Insufficient", "ADVANCE pay when balance low → 409", "P0", "Negative",
          "balance 10 due 100", "RECEPTIONIST",
          "ADVANCE 100",
          "1. Pay.",
          "409 insufficient advance.",
          "PATCH pay"),
        c("TS-15-017", "Refund", "Refund ≤ paidAmount creates REFUND payment", "P0", "Positive",
          "PAID invoice paid 500.", "ACCOUNTANT",
          "refund 200 method CASH",
          "1. Refund.",
          "paidAmount 300. Status PARTIALLY_PAID or ISSUED. Payment kind REFUND.",
          "PATCH refund"),
        c("TS-15-018", "Refund Over", "Refund > paid → 400", "P0", "Negative",
          "paid 100", "RECEPTIONIST",
          "refund 150",
          "1. Refund.",
          "400.",
          "PATCH refund"),
        c("TS-15-019", "Refund Advance Gap", "Refund ADVANCE collection does not restore balance (W-04)", "P0", "Positive",
          "Paid via ADVANCE; note balance before.", "ACCOUNTANT",
          "refund that payment amount",
          "1. Refund.\n2. Check advanceBalance.",
          "paidAmount reduced; advanceBalance NOT restored. Document W-04.",
          "PATCH refund"),
        c("TS-15-020", "Refund Methods", "UI refund methods CASH CARD UPI", "P1", "Positive",
          "Paid invoice.", "RECEPTIONIST",
          "refund UPI",
          "1. Refund.",
          "Succeeds.",
          "PATCH refund"),
        c("TS-15-021", "Pending Due", "While waiver PENDING, due still full (W-06)", "P0", "Positive",
          "PENDING waiver 200 on due 1000", "RECEPTIONIST",
          "Observe due on detail",
          "1. View invoice.",
          "Due still 1000 until approve.",
          "UI detail"),
        c("TS-15-022", "Merge Advance", "Patient merge sums advanceBalance", "P1", "Positive",
          "Two patients with advances — merge (TS-09).", "RECEPTIONIST",
          "—",
          "1. Merge.\n2. Check survivor balance.",
          "Summed.",
          "merge"),
        c("TS-15-023", "RBAC Advance", "Nurse cannot collect advance", "P0", "RBAC",
          "—", "NURSE",
          "POST advance",
          "1. Attempt.",
          "403.",
          "POST advance"),
        c("TS-15-024", "Insurance Pay", "INSURANCE method on invoice pay", "P2", "Positive",
          "Standalone due.", "RECEPTIONIST",
          "INSURANCE full",
          "1. Pay.",
          "Accepted.",
          "PATCH pay"),
        c("TS-15-025", "Discount After Partial", "Valid discount still above paid ok", "P1", "Positive",
          "paid 100 subtotal 1000", "RECEPTIONIST",
          "discount 50 → net 950",
          "1. Discount.",
          "ok net 950.",
          "PATCH discount"),
        c("TS-15-026", "Waiver Notify", "Request waiver notifies accountant", "P1", "Positive",
          "ACCOUNTANT has notifications.", "RECEPTIONIST",
          "waiver-request",
          "1. Request.\n2. Check accountant bell.",
          "Notification present.",
          "notifications"),
        c("TS-15-027", "Exact Advance", "ADVANCE exact balance to clear invoice", "P1", "Boundary",
          "balance=due=250", "RECEPTIONIST",
          "ADVANCE 250",
          "1. Pay.",
          "PAID. balance 0.",
          "PATCH pay"),
        c("TS-15-028", "Refund to Zero", "Full refund → ISSUED with paid 0", "P1", "Positive",
          "PAID 400 no discount.", "ACCOUNTANT",
          "refund 400",
          "1. Refund all.",
          "paidAmount 0 status ISSUED.",
          "PATCH refund"),
        c("TS-15-029", "Concurrent Note", "Document race if two full pays (no lock)", "P2", "Security",
          "due 100", "Two sessions",
          "parallel pay 100",
          "1. Optional parallel attempt.",
          "Record actual (possible double collect). Informational.",
          "PATCH pay"),
        c("TS-15-030", "Audit", "Discount waiver advance refund audited", "P1", "Positive",
          "After ops.", "SUPER_ADMIN",
          "audit log",
          "1. Verify actions.",
          "Entries present.",
          "audit-log"),
    ]


def ts16_cases():
    return [
        c("TS-16-001", "Daily", "Daily collections page filters one day", "P0", "Positive",
          "Payments today + yesterday.", "RECEPTIONIST",
          "/billing/collections date=today",
          "1. Open.\n2. Switch date.",
          "Shows only selected day's payments. Net by method. Doctor breakdown.",
          "/billing/collections"),
        c("TS-16-002", "Daily Net", "Net = collections - refunds per method", "P0", "Positive",
          "CASH collect 500 + CASH refund 100 same day.", "ACCOUNTANT",
          "—",
          "1. View collections.",
          "CASH net 400. Refunds listed separately.",
          "collections page"),
        c("TS-16-003", "Advance In Collections", "ADVANCE deposits appear in daily totals", "P1", "Positive",
          "Advance collected today.", "RECEPTIONIST",
          "—",
          "1. View.",
          "Included in non-REFUND totals.",
          "collections"),
        c("TS-16-004", "Doctor Bucket", "Unassigned bills under Unassigned / other", "P1", "Positive",
          "Standalone invoice payment.", "RECEPTIONIST",
          "—",
          "1. View by doctor.",
          "Shows Unassigned / other bills.",
          "collections"),
        c("TS-16-005", "Monthly", "Monthly report for YYYY-MM", "P0", "Positive",
          "Payments in month.", "ACCOUNTANT",
          "/billing/reports month",
          "1. Select month.",
          "collectedTotal refundTotal net paymentCount byMethod doctorRows outstanding.",
          "loadBillingReport"),
        c("TS-16-006", "Outstanding", "Outstanding list not limited to selected month", "P0", "Positive",
          "Old ISSUED unpaid + current month filter", "ACCOUNTANT",
          "—",
          "1. Open reports.",
          "Old dues appear (due>0.009) up to 200. Document behavior.",
          "reports"),
        c("TS-16-007", "CSV Collections", "Export collections CSV", "P0", "Positive",
          "—", "ACCOUNTANT",
          "GET /api/billing/reports?month=&kind=collections",
          "1. Download.",
          "CSV columns: Received at, Patient, Invoice, Method, Amount.",
          "GET reports"),
        c("TS-16-008", "CSV Dues", "Export dues CSV", "P0", "Positive",
          "—", "ACCOUNTANT",
          "kind=dues",
          "1. Download.",
          "CSV: Invoice, Patient, Net, Paid, Due, Status, Issued.",
          "GET reports"),
        c("TS-16-009", "No Filters", "No doctor/method query filters on API", "P2", "Positive",
          "—", "ACCOUNTANT",
          "API params",
          "1. Inspect.",
          "Only month + kind. Breakdowns computed not filterable. Pass.",
          "API"),
        c("TS-16-010", "Send Receipt", "WhatsApp send bill_receipt for ISSUED/PAID", "P0", "Positive",
          "Invoice not VOID/DRAFT. Phone ≥10.", "RECEPTIONIST",
          "send on detail",
          "1. Send WhatsApp.",
          "PDF uploaded if provider. OutboundMessage. Audit BILL_RECEIPT_SENT or FAILED.",
          "POST /api/invoices/[id]/send"),
        c("TS-16-011", "Send Block Status", "Cannot send DRAFT/VOID", "P1", "Negative",
          "If can set DRAFT/VOID in DB — else Skip.", "RECEPTIONIST",
          "send",
          "1. Send.",
          "400. UI hides button.",
          "POST send"),
        c("TS-16-012", "Send Phone", "Send fails short phone", "P0", "Negative",
          "Patient phone 123.", "RECEPTIONIST",
          "send",
          "1. Send.",
          "400.",
          "POST send"),
        c("TS-16-013", "Send Channel", "EMAIL/SMS rejected by schema — WhatsApp only", "P1", "Negative",
          "—", "RECEPTIONIST",
          "API channel EMAIL",
          "1. POST send EMAIL.",
          "Validation fail.",
          "POST send"),
        c("TS-16-014", "PDF Contents", "Receipt PDF has waiver only if APPROVED", "P1", "Positive",
          "A) pending waiver B) approved waiver", "RECEPTIONIST",
          "Print both",
          "1. Compare PDFs.",
          "Waiver line only when approved + amount>0.",
          "bill-receipt-pdf"),
        c("TS-16-015", "Received By", "Signature from latest COLLECTION payment", "P1", "Positive",
          "Collector has ACTIVE signature.", "RECEPTIONIST",
          "Pay then print",
          "1. PDF.",
          "Received by block present.",
          "receipt-collector"),
        c("TS-16-016", "RBAC Reports", "Nurse cannot open reports when receptionist toggle is off", "P0", "RBAC",
          "nurseAsReceptionist false.", "NURSE",
          "/billing/reports",
          "1. Open.",
          "Denied.",
          "page"),
        c("TS-16-017", "Month Boundary", "Payment at month edge counted correctly", "P1", "Boundary",
          "Payment on 1st 00:00 local if possible.", "ACCOUNTANT",
          "two months",
          "1. Compare reports.",
          "Falls in correct month range [start, nextMonth).",
          "reports"),
        c("TS-16-018", "Day Close", "No cash-drawer lock — collections is reconciliation only", "P2", "Positive",
          "—", "ACCOUNTANT",
          "—",
          "1. Confirm no day-close lock action.",
          "Pass — informational.",
          "UI"),
        c("TS-16-019", "Filename", "PDF filename bill-{invoiceNo sanitized}", "P2", "Positive",
          "Invoice with special chars if any.", "RECEPTIONIST",
          "Download",
          "1. Check filename.",
          "bill-INV_....pdf style.",
          "rules.ts"),
        c("TS-16-020", "Failed Send Audit", "Failed WhatsApp still audits FAILURE", "P2", "Positive",
          "Break provider / invalid media env.", "RECEPTIONIST",
          "send",
          "1. Force fail if possible.",
          "BILL_RECEIPT_FAILED audit. Or Skip if cannot force.",
          "send.ts"),
        c("TS-16-021", "Tenant", "Reports only own hospital data", "P0", "Security",
          "H1 vs H4 payments.", "ACCOUNTANT H1",
          "reports",
          "1. View.",
          "Only H1 totals.",
          "reports"),
        c("TS-16-022", "List Link", "Billing home links to advance collections reports", "P2", "Positive",
          "—", "RECEPTIONIST",
          "/billing",
          "1. Click links.",
          "All navigate.",
          "/billing"),
        c("TS-16-023", "Nurse Receptionist On", "Nurse can open collections and reports when toggle is on", "P1", "Positive",
          "nurseAsReceptionist true. Payments exist.", "NURSE",
          "/billing/collections /billing/reports",
          "1. Open both pages.\n2. Optional: send WhatsApp receipt if phone valid.",
          "Pages load with H1 data. Send allowed for billing roles including opted-in nurse.",
          "/billing/collections + reports + send"),
    ]


def ts17_cases():
    return [
        c("TS-17-001", "Create", "Any signed-in user can create ticket", "P0", "Positive",
          "Logged in receptionist.", "RECEPTIONIST",
          "/helpdesk/new subject+body",
          "1. Create.",
          "Ticket OPEN. Visible to handlers. Notifications to watchers.",
          "POST /api/helpdesk/tickets"),
        c("TS-17-002", "Public Help", "Public help-request creates ticket with SLA", "P0", "Positive",
          "Anonymous or OTP path per UI.", "Anonymous",
          "Valid help request payload",
          "1. Submit public help.",
          "Ticket created with SLA due dates by priority. URGENT mapped to HIGH if applicable.",
          "POST /api/public/help-request"),
        c("TS-17-003", "Auth Ticket No SLA", "Authenticated create may omit SLA fields", "P1", "Positive",
          "—", "SUPER_ADMIN",
          "Create via /helpdesk/new",
          "1. Create.\n2. Inspect SLA fields.",
          "Document: may lack SLA vs public — Pass if matches code.",
          "POST tickets"),
        c("TS-17-004", "Visibility", "Staff sees own; SUPER hospital; HELPDESK/SAAS all", "P0", "RBAC",
          "Tickets across hospitals.", "Various",
          "/helpdesk",
          "1. List as each role.",
          "Scoped correctly.",
          "GET tickets"),
        c("TS-17-005", "Reply Agent", "Agent reply → IN_PROGRESS then WAITING_REPLY", "P0", "Positive",
          "OPEN ticket.", "HELPDESK",
          "message reply",
          "1. Reply.",
          "Status moves per messages route; firstResponseAt set.",
          "POST .../messages"),
        c("TS-17-006", "Reply Requester", "Requester reply on RESOLVED reopens OPEN", "P0", "Positive",
          "RESOLVED ticket.", "RECEPTIONIST (creator)",
          "reply",
          "1. Reply.",
          "Status OPEN (+ reopen count). ",
          "POST messages"),
        c("TS-17-007", "Internal Note", "Internal note no status change; helpdesk only", "P1", "Positive",
          "OPEN.", "HELPDESK / RECEPTIONIST",
          "internal note",
          "1. Agent adds note.\n2. Staff attempt.",
          "Agent ok status unchanged. Staff cannot add internal.",
          "POST messages"),
        c("TS-17-008", "Closed", "CLOSED ticket rejects new replies", "P0", "Negative",
          "CLOSED.", "HELPDESK",
          "reply",
          "1. Reply.",
          "Rejected.",
          "POST messages"),
        c("TS-17-009", "Status PATCH", "Helpdesk can set status manually", "P0", "Positive",
          "OPEN.", "HELPDESK",
          "IN_PROGRESS / RESOLVED / CLOSED",
          "1. PATCH statuses.",
          "Timestamps firstResponseAt resolvedAt closedAt set appropriately.",
          "PATCH /api/helpdesk/tickets/[id]"),
        c("TS-17-010", "Escalate", "Escalate → ESCALATED", "P0", "Positive",
          "Non-terminal ticket.", "HELPDESK",
          "escalate",
          "1. Escalate.",
          "ESCALATED. Notify watchers.",
          "POST .../escalate"),
        c("TS-17-011", "Escalate Block", "Cannot escalate CLOSED/RESOLVED/already ESCALATED", "P1", "Negative",
          "CLOSED.", "HELPDESK",
          "escalate",
          "1. Escalate.",
          "Rejected.",
          "POST escalate"),
        c("TS-17-012", "Escalated Reply", "Agent reply does not leave ESCALATED automatically", "P1", "Positive",
          "ESCALATED.", "HELPDESK",
          "reply",
          "1. Reply.",
          "Stays ESCALATED (per code). Document actual.",
          "POST messages"),
        c("TS-17-013", "Priority", "UI priorities LOW NORMAL HIGH (URGENT schema)", "P1", "Positive",
          "—", "HELPDESK",
          "Set HIGH",
          "1. Create/update priority.",
          "HIGH accepted. URGENT may be schema-only.",
          "tickets"),
        c("TS-17-014", "SLA Breach", "Queue shows breached SLA when past due", "P1", "Positive",
          "Public ticket with past sla dates (or wait).", "HELPDESK",
          "queue",
          "1. View queue indicators.",
          "Breach highlighted if implemented.",
          "helpdesk-queue"),
        c("TS-17-015", "Support RESET_PASSWORD", "HELPDESK runs RESET_PASSWORD support action", "P0", "Positive",
          "Target hospital staff user.", "HELPDESK",
          "action RESET_PASSWORD",
          "1. Run from ticket.",
          "Password reset path executed; thread note; audit SUPPORT_ACTION. Not platform account.",
          "POST .../actions"),
        c("TS-17-016", "Support FIX_MOBILE", "FIX_MOBILE updates mobile with validation", "P1", "Positive",
          "Target user.", "HELPDESK",
          "new valid mobile",
          "1. Run.",
          "Mobile updated; note+audit.",
          "actions"),
        c("TS-17-017", "Support Others", "MARK_VERIFIED REACTIVATE CLEAR_OTP_LOCK SIGN_OUT_ALL", "P0", "Positive",
          "Appropriate target states.", "SOFTWARE_ADMIN",
          "each action",
          "1. Run each.",
          "Each succeeds with note+audit.",
          "actions"),
        c("TS-17-018", "Support Admin Tier", "EXTEND_TRIAL etc catalog only not runnable", "P1", "Negative",
          "—", "HELPDESK",
          "EXTEND_TRIAL via API",
          "1. Attempt.",
          "Not in runSupportAction — rejected.",
          "actions"),
        c("TS-17-019", "Support RBAC", "SUPER_ADMIN cannot run support actions", "P0", "RBAC",
          "—", "SUPER_ADMIN",
          "RESET_PASSWORD",
          "1. Run.",
          "403 canRunSupportAction false.",
          "actions"),
        c("TS-17-020", "Support Closed", "Cannot run support on CLOSED", "P1", "Negative",
          "CLOSED ticket.", "HELPDESK",
          "action",
          "1. Run.",
          "Rejected.",
          "actions"),
        c("TS-17-021", "Assign", "Assign ticket to helpdesk user", "P1", "Positive",
          "Two helpdesk agents.", "SOFTWARE_ADMIN",
          "assigneeId",
          "1. PATCH assign.",
          "Assignee set; visible in queue.",
          "PATCH ticket"),
        c("TS-17-022", "Rate Limit Public", "Public help rate limit 8/15min", "P2", "Security",
          "Fresh IP.", "Anonymous",
          "9 requests",
          "1. Spam public help.",
          "429 after 8.",
          "POST help-request"),
        c("TS-17-023", "Detail", "Ticket detail shows thread + status history", "P1", "Positive",
          "Ticket with messages.", "HELPDESK",
          "/helpdesk/[id]",
          "1. Open.",
          "Thread visible.",
          "detail"),
        c("TS-17-024", "Platform Team", "Only SOFTWARE_ADMIN manages helpdesk team", "P0", "RBAC",
          "—", "HELPDESK",
          "/platform/helpdesk-team",
          "1. Open.",
          "Denied for HELPDESK.",
          "platform page"),
        c("TS-17-025", "Target Guard", "Support action rejects platform target accounts", "P0", "Security",
          "Target SOFTWARE_ADMIN id.", "HELPDESK",
          "RESET_PASSWORD",
          "1. Run.",
          "Rejected.",
          "actions"),
        c("TS-17-026", "Hospital Match", "Support action hospital must match ticket/user", "P1", "Security",
          "Cross-hospital target.", "HELPDESK",
          "action",
          "1. Run.",
          "Rejected hospital mismatch.",
          "actions"),
    ]


def ts18_cases():
    return [
        c("TS-18-001", "Board Location", "/board redirects to home; chat on /", "P0", "Positive",
          "Hospital user.", "RECEPTIONIST",
          "/board and /",
          "1. Open /board.\n2. Find BoardChat on home.",
          "/board → /. Board visible on home.",
          "/board /"),
        c("TS-18-002", "Post", "Any hospital staff can post", "P0", "Positive",
          "—", "NURSE",
          "title≥2 body≥2",
          "1. Post announcement.",
          "Created. Others notified except author. Audit BOARD_POST_CREATED.",
          "POST /api/board"),
        c("TS-18-003", "Validation", "Title 2–120 Body 2–4000", "P1", "Boundary",
          "—", "RECEPTIONIST",
          "A) title 1 char B) body 1 char C) huge body",
          "1. Post.",
          "A/B fail. Over max fail.",
          "POST board"),
        c("TS-18-004", "Reply", "Staff can reply 2–2000 chars", "P0", "Positive",
          "Existing post.", "DOCTOR",
          "reply text",
          "1. Reply.",
          "Reply created. Author notified if different. Audit BOARD_REPLY_CREATED.",
          "POST .../replies"),
        c("TS-18-005", "Pin", "Only SUPER_ADMIN pin/unpin", "P0", "RBAC",
          "Post exists.", "RECEPTIONIST / SUPER_ADMIN",
          "pin",
          "1. Receptionist pin.\n2. Super pin.",
          "Recep 403. Super ok. Audit PINNED/UNPINNED.",
          "PATCH board/[id]"),
        c("TS-18-006", "Delete Post", "Author or SUPER_ADMIN delete post", "P0", "Positive",
          "Own post + others post.", "DOCTOR / SUPER_ADMIN",
          "delete",
          "1. Author deletes own.\n2. Other doctor cannot.\n3. Super deletes any.",
          "Permissions enforced. Audit DELETED.",
          "DELETE board/[id]"),
        c("TS-18-007", "Delete Reply", "Author or SUPER_ADMIN delete reply", "P1", "Positive",
          "Reply exists.", "Various",
          "delete reply",
          "1. Attempt as author, other, super.",
          "Author/super ok only.",
          "DELETE replies/[replyId]"),
        c("TS-18-008", "Notify", "New post notifies hospital staff except author", "P0", "Positive",
          "Multiple staff.", "RECEPTIONIST",
          "post",
          "1. Post.\n2. Check other users' notifications.",
          "Others receive; author does not.",
          "notifications"),
        c("TS-18-009", "Realtime", "Notification appears via socket if connected", "P2", "Positive",
          "Socket connected.", "DOCTOR",
          "Another user posts",
          "1. Watch bell.",
          "Realtime update or on refresh. Document.",
          "socket.io"),
        c("TS-18-010", "Templates", "Message templates exist for reminder otp summary etc", "P1", "Positive",
          "Code/env.", "SOFTWARE_ADMIN",
          "templates.ts keys",
          "1. Confirm keys used by send flows.",
          "appointment_reminder otp investigation_list visit_summary medical_certificate bill_receipt.",
          "templates.ts"),
        c("TS-18-011", "Opt-out", "Patient whatsappOptIn false skips WA", "P1", "Positive",
          "Patient opted out. APPROVED summary.", "DOCTOR",
          "send summary",
          "1. Send.",
          "Delivery skipped/failed per opt-out rules.",
          "deliverMessage"),
        c("TS-18-012", "Queue Retry", "Outbound queue retries up to 3 then FAILED", "P2", "Positive",
          "Force failing provider for reminder.", "RECEPTIONIST",
          "remind appointment",
          "1. Trigger remind.\n2. Observe attempts.",
          "Max 3 then FAILED. Or Skip if cannot force.",
          "queue.ts"),
        c("TS-18-013", "Console Provider", "Without WA token messages log to console", "P1", "Positive",
          "No ASKEVA/WA token. OTP_DUMMY ok.", "Any",
          "OTP or send",
          "1. Trigger message.",
          "Console provider logs; app does not crash.",
          "providers"),
        c("TS-18-014", "Notifications API", "User can list/mark notifications", "P1", "Positive",
          "Unread exist.", "DOCTOR",
          "GET/PATCH notifications",
          "1. Open bell.\n2. Mark read.",
          "List works; read state updates.",
          "/api/notifications"),
        c("TS-18-015", "Platform No Board", "Platform roles cannot post hospital board", "P0", "RBAC",
          "Login SOFTWARE_ADMIN.", "SOFTWARE_ADMIN",
          "POST board",
          "1. Attempt.",
          "403 hospital actor required.",
          "POST board"),
        c("TS-18-016", "Title Auto", "Chat UI may derive title from first line", "P2", "Positive",
          "—", "RECEPTIONIST",
          "Single box message",
          "1. Post via chat UI.",
          "Title auto from first line if implemented.",
          "BoardChat"),
        c("TS-18-017", "Pin Order", "Pinned posts sort above others", "P1", "Positive",
          "Pinned + unpinned.", "SUPER_ADMIN",
          "—",
          "1. View board.",
          "Pinned first.",
          "listAnnouncements"),
        c("TS-18-018", "Tenant", "Board posts isolated per hospital", "P0", "Security",
          "H1 and H4 posts.", "RECEPTIONIST H1",
          "—",
          "1. View board.",
          "Only H1 posts.",
          "board"),
    ]


def ts19_cases():
    return [
        c("TS-19-001", "Access Hospital", "Only SUPER_ADMIN views /hospital/audit-log", "P0", "RBAC",
          "—", "RECEPTIONIST / SUPER_ADMIN",
          "/hospital/audit-log",
          "1. Open as each.",
          "Recep denied. Super sees up to 500 rows.",
          "page"),
        c("TS-19-002", "Access Platform", "SOFTWARE_ADMIN views per-hospital audit", "P0", "Positive",
          "—", "SOFTWARE_ADMIN",
          "/platform/audit-log → H1",
          "1. Open.",
          "Logs for H1 visible.",
          "platform audit"),
        c("TS-19-003", "API", "GET /api/hospital/audit-log SUPER_ADMIN 200 rows", "P1", "Positive",
          "—", "SUPER_ADMIN",
          "GET",
          "1. Call API.",
          "200 list ≤200.",
          "GET /api/hospital/audit-log"),
        c("TS-19-004", "Shape", "Record has actor action entity summary metadata createdAt", "P0", "Positive",
          "Any log row.", "SUPER_ADMIN",
          "—",
          "1. Inspect one entry.",
          "Fields: actorUserId/Username/Role, action, entity, entityId, summary, metadata(JSON+IP), hospitalId.",
          "UI/API"),
        c("TS-19-005", "Auth Actions", "LOGIN LOGIN_FAILED LOGOUT present after TS-02", "P0", "Positive",
          "After login tests.", "SUPER_ADMIN",
          "—",
          "1. Find actions.",
          "Present.",
          "audit"),
        c("TS-19-006", "Patient Actions", "PATIENT_REGISTERED UPDATED MERGED FAMILY", "P0", "Positive",
          "After TS-09.", "SUPER_ADMIN",
          "—",
          "1. Find.",
          "Present.",
          "audit"),
        c("TS-19-007", "User Actions", "USER_CREATED UPDATED SIGNATURE_*", "P0", "Positive",
          "After TS-06.", "SUPER_ADMIN",
          "—",
          "1. Find.",
          "Present.",
          "audit"),
        c("TS-19-008", "Billing Actions", "Advance discount waiver payment audits", "P1", "Positive",
          "After TS-15.", "SUPER_ADMIN",
          "—",
          "1. Find.",
          "Present.",
          "audit"),
        c("TS-19-009", "Redaction", "Passwords and image blobs redacted in diffs", "P0", "Security",
          "Update user password / upload logo.", "SUPER_ADMIN",
          "audit metadata",
          "1. Inspect diff.",
          "password/image not raw in metadata (diffAuditFields).",
          "audit-changes"),
        c("TS-19-010", "Helpdesk", "HELPDESK_* and SUPPORT_ACTION logged", "P1", "Positive",
          "After TS-17.", "SOFTWARE_ADMIN",
          "—",
          "1. Find.",
          "Present.",
          "audit"),
        c("TS-19-011", "Board", "BOARD_* actions logged", "P2", "Positive",
          "After TS-18.", "SUPER_ADMIN",
          "—",
          "1. Find.",
          "Present.",
          "audit"),
        c("TS-19-012", "Tenant", "Hospital audit does not show other hospital", "P0", "Security",
          "H1 and H4 activity.", "SUPER_ADMIN H1",
          "—",
          "1. View H1 log.",
          "Only H1 hospitalId rows.",
          "audit"),
        c("TS-19-013", "Registration", "Hospital registration audited", "P1", "Positive",
          "After TS-01.", "SOFTWARE_ADMIN",
          "—",
          "1. Find registration action.",
          "Present on platform/hospital log.",
          "audit"),
        c("TS-19-014", "RBAC API", "Non-super GET audit-log 403", "P0", "RBAC",
          "—", "DOCTOR",
          "GET audit-log",
          "1. Call.",
          "403.",
          "GET /api/hospital/audit-log"),
    ]


def ts20_cases():
    return [
        c("TS-20-001", "Matrix Front Desk", "RECEPTIONIST: patients Y, users N, settings N, assess N", "P0", "RBAC",
          "H1 fixtures.", "RECEPTIONIST",
          "Try each area",
          "1. Probe pages/APIs.",
          "Patients/appointments/billing Y. /hospital/users N. settings N. assessment approve N. vitals N.",
          "multi"),
        c("TS-20-002", "Matrix Doctor", "DOCTOR: assess Y, users N, waiver approve N, start own only", "P0", "RBAC",
          "—", "DOCTOR",
          "—",
          "1. Probe.",
          "Matches authz/hospital.ts.",
          "multi"),
        c("TS-20-003", "Matrix Nurse", "NURSE default: vitals Y, billing N, certificates N, front desk N", "P0", "RBAC",
          "nurseAsReceptionist false.", "NURSE",
          "—",
          "1. Probe.",
          "Vitals/nurse Y. Billing N. Cert issue N. Patient register/edit N. Queue manage N. See TS-20-031 when toggle on.",
          "multi"),
        c("TS-20-004", "Matrix Accountant", "ACCOUNTANT: billing+waiver approve Y, clinical edit N", "P0", "RBAC",
          "—", "ACCOUNTANT",
          "—",
          "1. Probe.",
          "Billing reports waiver decide Y. Patient demographics edit N. Assessment N.",
          "multi"),
        c("TS-20-005", "Matrix Super", "SUPER_ADMIN: hospital admin surfaces Y, platform N", "P0", "RBAC",
          "—", "SUPER_ADMIN",
          "/platform /hospital/*",
          "1. Probe.",
          "Hospital admin Y. Platform console N.",
          "multi"),
        c("TS-20-006", "Matrix SaaS", "SOFTWARE_ADMIN: platform Y, hospital scoped APIs N", "P0", "RBAC",
          "—", "SOFTWARE_ADMIN",
          "GET /api/patients",
          "1. Call hospital API.",
          "403 Hospital access required. Platform pages Y.",
          "multi"),
        c("TS-20-007", "Matrix Helpdesk", "HELPDESK: helpdesk Y, platform hospitals N, board N", "P0", "RBAC",
          "—", "HELPDESK",
          "—",
          "1. Probe.",
          "Helpdesk Y. Create hospital N. Board N.",
          "multi"),
        c("TS-20-008", "Tenant Patient", "H1 user cannot GET H4 patient", "P0", "Security",
          "P6 in H4.", "RECEPTIONIST H1",
          "patient id",
          "1. GET.",
          "404/403.",
          "GET patients/[id]"),
        c("TS-20-009", "Tenant Appointment", "H1 cannot PATCH H4 appointment", "P0", "Security",
          "H4 appt.", "DOCTOR H1",
          "—",
          "1. start/complete.",
          "404/403.",
          "PATCH appointments"),
        c("TS-20-010", "Tenant Invoice", "H1 cannot pay H4 invoice", "P0", "Security",
          "H4 invoice.", "ACCOUNTANT H1",
          "—",
          "1. pay.",
          "404/403.",
          "PATCH invoices"),
        c("TS-20-011", "Tenant Certificate", "H1 cannot void H4 certificate", "P0", "Security",
          "H4 cert.", "DOCTOR H1",
          "—",
          "1. void.",
          "404/403.",
          "POST void"),
        c("TS-20-012", "Tenant Leave", "H1 cannot approve H4 leave", "P1", "Security",
          "H4 leave id.", "SUPER_ADMIN H1",
          "—",
          "1. approve.",
          "404/403.",
          "PATCH leaves"),
        c("TS-20-013", "Tenant Board", "H1 cannot delete H4 post", "P1", "Security",
          "H4 post id.", "SUPER_ADMIN H1",
          "—",
          "1. delete.",
          "404/403.",
          "DELETE board"),
        c("TS-20-014", "Inactive User Session", "Deactivated user sessions die", "P0", "Security",
          "Active session then deactivate.", "SUPER_ADMIN",
          "—",
          "1. Deactivate user.\n2. Use old cookie.",
          "Treated logged out; sessions deleted.",
          "session-user"),
        c("TS-20-015", "Inactive Hospital Session", "Stopped hospital kills staff sessions", "P0", "Security",
          "Stop hospital via platform.", "SOFTWARE_ADMIN",
          "—",
          "1. Stop.\n2. Staff cookie.",
          "Logged out.",
          "session-user"),
        c("TS-20-016", "Module Nav", "Current plans cannot open pharmacy/lab/wards URLs", "P0", "RBAC",
          "H1 on CLINIC/STARTER/GROWTH.", "SUPER_ADMIN",
          "/pharmacy /lab /wards",
          "1. Navigate.",
          "Redirect/hidden/403 — modules not on current plans.",
          "nav+guards"),
        c("TS-20-017", "Seat Gate", "Cannot exceed seats via users or join", "P0", "Security",
          "Seats full.", "SUPER_ADMIN",
          "create/join",
          "1. Attempt both.",
          "403 both paths.",
          "users + join"),
        c("TS-20-018", "View Mode Cookie", "mederp_view_mode not forgeable into unauthorized doctor", "P1", "Security",
          "SUPER without doctor staff.", "SUPER_ADMIN",
          "Set cookie doctor manually",
          "1. Set cookie.\n2. Browse.",
          "Server still enforces eligibility / 403 on API.",
          "view-mode"),
        c("TS-20-019", "IDOR Guess", "Sequential id guess across tenants fails", "P0", "Security",
          "Collect H4 ids while H1 session.", "RECEPTIONIST H1",
          "Several entity ids",
          "1. Probe patients appointments invoices.",
          "No data leak.",
          "APIs"),
        c("TS-20-020", "Join Platform", "Platform cannot join hospital", "P0", "RBAC",
          "—", "SOFTWARE_ADMIN",
          "POST join",
          "1. Join.",
          "403.",
          "join-requests"),
        c("TS-20-021", "Helpdesk Isolation", "Hospital staff cannot see other hospital tickets", "P0", "Security",
          "Tickets in H1 and H4.", "SUPER_ADMIN H1",
          "/helpdesk",
          "1. List.",
          "Only own hospital (+ own created).",
          "helpdesk"),
        c("TS-20-022", "Billing Roles", "Confirm BILLING_ROLES constant membership", "P1", "RBAC",
          "—", "Each role",
          "Open /billing",
          "1. SUPER REC ACC DOC Y; others N.",
          "Matches authz.",
          "/billing"),
        c("TS-20-023", "Print Roles", "PRINT_SUMMARY_ROLES send summary", "P1", "RBAC",
          "APPROVED visit.", "NURSE / ACCOUNTANT",
          "summary send",
          "1. Nurse send.\n2. Accountant send.",
          "Nurse Y. Accountant N.",
          "summary/send"),
        c("TS-20-024", "Waiver Roles", "Only SUPER+ACCOUNTANT decide waiver", "P0", "RBAC",
          "PENDING waiver.", "DOCTOR",
          "waiver-decide",
          "1. Decide.",
          "403.",
          "PATCH"),
        c("TS-20-025", "Cookie Flags", "Session cookie httpOnly SameSite strict", "P1", "Security",
          "After login.", "Any",
          "DevTools cookies",
          "1. Inspect mederp_session.",
          "httpOnly; SameSite=strict; Secure per env.",
          "auth.ts"),
        c("TS-20-026", "Bearer Theft Note", "Bearer token in login response — treat as secret", "P2", "Security",
          "Login response.", "Any",
          "sessionToken",
          "1. Confirm token present.\n2. Ensure not logged to console in prod UI.",
          "Informational Pass/Fail on UI leakage.",
          "login response"),
        c("TS-20-027", "Cross Role Certificate", "NURSE cannot issue certificate", "P0", "RBAC",
          "—", "NURSE",
          "POST certificates",
          "1. Issue.",
          "403.",
          "POST certificates"),
        c("TS-20-028", "Cross Role Vitals", "ACCOUNTANT cannot post vitals", "P0", "RBAC",
          "Today visit.", "ACCOUNTANT",
          "vitals",
          "1. POST.",
          "403.",
          "POST vitals"),
        c("TS-20-029", "Software Admin Stop", "Stopping hospital blocks all hospital roles", "P0", "Security",
          "H4 or disposable hospital.", "SOFTWARE_ADMIN",
          "isActive false",
          "1. Stop.\n2. Login each role.",
          "All hospital staff blocked.",
          "platform hospitals"),
        c("TS-20-030", "Matrix Nurse Receptionist", "Toggle ON: nurse gets receptionist front desk, still not admin/doctor", "P0", "RBAC",
          "nurseAsReceptionist true.", "NURSE",
          "Probe patients, billing, users, settings, assessment, certificates, vitals",
          "1. Register/edit patient Y.\n2. Queue/appointments manage Y.\n3. Billing collect Y.\n4. /hospital/users N.\n5. /hospital/settings N.\n6. Assessment approve N.\n7. Certificate issue N.\n8. Vitals Y.\n9. Waiver decide N.",
          "Front desk Y. Clinical nurse duties stay. Superadmin/doctor-only actions stay denied.",
          "multi"),
        c("TS-20-031", "Matrix Receptionist Unchanged", "Dedicated receptionist still has front desk when nurse toggle is on", "P0", "RBAC",
          "Toggle ON. U-H1-REC exists.", "RECEPTIONIST",
          "Same probes as TS-20-001",
          "1. Repeat receptionist matrix.",
          "Patients/appointments/billing Y. Users/settings/assess/vitals N. Toggle does not remove the Receptionist role.",
          "multi"),
        c("TS-20-032", "Summary Matrix Sign-off", "Attach completed RBAC checklist to run", "P0", "Positive",
          "TS-20-001..031 done.", "Tester",
          "Checklist",
          "1. Mark suite Pass only if no unexpected allows.",
          "Sign-off in Index notes.",
          "Index"),
    ]
