"""TS-09 through TS-13 manual cases."""
from case_util import c


def ts09_cases():
    return [
        c("TS-09-001", "Access", "Clinical roles + ACCOUNTANT can list patients", "P0", "RBAC",
          "Patients exist.", "RECEPTIONIST / DOCTOR / NURSE / ACCOUNTANT",
          "/patients",
          "1. Open list as each.",
          "List loads. PHARMACIST (if any) not in clinical view — expect deny if tested.",
          "GET /patients"),
        c("TS-09-002", "Register Access", "Receptionist/Super/Doctor can open new patient", "P0", "RBAC",
          "canRegisterPatient true. nurseAsReceptionist false.", "RECEPTIONIST",
          "/patients/new",
          "1. Open form.",
          "Form available. Nurse cannot open /patients/new on default (see TS-09-039).",
          "/patients/new"),
        c("TS-09-003", "Create", "Happy path creates patient with UHID", "P0", "Positive",
          "Front desk logged in.", "RECEPTIONIST",
          "P1: Ramesh Kumar\nDOB 1985-03-15\nMALE\nPhone 9876510001",
          "1. Fill required fields.\n2. Save.",
          "Patient created. MRN/UHID format {HOSPITALCODE}-{YYYY}-NNNNN. Audit PATIENT_REGISTERED. Appears in list.",
          "POST /api/patients"),
        c("TS-09-004", "Validation", "firstName, age, gender required (unless unnamed infant)", "P0", "Negative",
          "—", "RECEPTIONIST",
          "Omit each required field in turn. unnamedInfant false. Date of birth is optional.",
          "1. Submit incomplete.",
          "400 'First name and age are required.' Gender still required. Unnamed infant path is TS-09-042.",
          "POST /api/patients"),
        c("TS-09-005", "Gender", "Gender must be MALE FEMALE OTHER", "P1", "Boundary",
          "—", "RECEPTIONIST",
          "gender: UNKNOWN",
          "1. Submit.",
          "Rejected.",
          "POST /api/patients"),
        c("TS-09-006", "Optional", "lastName may be empty; clinical fields optional", "P1", "Positive",
          "—", "RECEPTIONIST",
          "firstName only + age + gender",
          "1. Save.",
          "Created with lastName ''.",
          "POST /api/patients"),
        c("TS-09-007", "Photo", "Valid image photo accepted; invalid/oversized rejected", "P1", "Boundary",
          "—", "RECEPTIONIST",
          "A) small jpeg data-url\nB) >900k chars or wrong mime",
          "1. Register with each.",
          "A ok. B rejected by sanitize.",
          "POST /api/patients"),
        c("TS-09-008", "ID Proof", "idProofType enum values accepted", "P2", "Positive",
          "—", "RECEPTIONIST",
          "AADHAAR / PAN / PASSPORT / DRIVING_LICENSE / VOTER_ID / OTHER + number",
          "1. Save with AADHAAR.",
          "Stored. Invalid type rejected.",
          "POST /api/patients"),
        c("TS-09-009", "Age Display", "Infant <24 months shows months", "P1", "Positive",
          "—", "RECEPTIONIST",
          "P3 DOB within last 24 months",
          "1. Register P3.\n2. View list + detail.",
          "Age displays as 'N M' months (ageLabel), not years, on /patients and patient detail.",
          "patient list + detail UI"),
        c("TS-09-010", "Duplicate", "Same first+last+DOB → 409 duplicates", "P0", "Negative",
          "P1 exists.", "RECEPTIONIST",
          "P4 same name+DOB different phone",
          "1. Save without force.",
          "409 with duplicates[] (max 8). Options: Register anyway / Add as family.",
          "POST /api/patients"),
        c("TS-09-011", "Duplicate", "Same phone → 409 (when not familyOf)", "P0", "Negative",
          "P1 phone 9876510001.", "RECEPTIONIST",
          "Different name, same phone",
          "1. Save.",
          "409 phone duplicate.",
          "POST /api/patients"),
        c("TS-09-012", "Duplicate", "Same idProofNumber → 409", "P1", "Negative",
          "Patient with idProofNumber X.", "RECEPTIONIST",
          "Same idProofNumber",
          "1. Save.",
          "409.",
          "POST /api/patients"),
        c("TS-09-013", "Force", "force:true registers despite duplicates", "P0", "Positive",
          "409 panel showing.", "RECEPTIONIST",
          "force true",
          "1. Register anyway.",
          "New UHID created. Audit PATIENT_REGISTERED.",
          "POST /api/patients force"),
        c("TS-09-014", "Family Create", "Register with familyOfPatientId inherits phone/address/insurance", "P0", "Positive",
          "P1 exists.", "RECEPTIONIST",
          "P2 Sita Kumar familyOf P1 relation SPOUSE",
          "1. Add as family from duplicate UI or form.",
          "Created with inherited phone if blank. PatientFamily link. Family group code FAM-{CODE}-NNNNN. Audit FAMILY_MEMBER_REGISTERED.",
          "POST /api/patients"),
        c("TS-09-015", "Family Phone Skip", "Duplicate phone check skipped when familyOfPatientId set", "P0", "Positive",
          "P1 phone shared.", "RECEPTIONIST",
          "P3 child with same phone via familyOf",
          "1. Register family member same phone.",
          "Succeeds without 409 phone duplicate.",
          "POST /api/patients"),
        c("TS-09-016", "Family Link API", "POST family link between existing patients", "P0", "Positive",
          "Two patients.", "RECEPTIONIST",
          "relation CHILD",
          "1. Link on patient detail.",
          "Upsert PatientFamily. Audit PATIENT_FAMILY_LINKED. Front desk only.",
          "POST /api/patients/[id]/family"),
        c("TS-09-017", "Family RBAC", "Doctor cannot create family link via API", "P1", "RBAC",
          "—", "DOCTOR",
          "family POST",
          "1. Attempt.",
          "403 front desk only.",
          "POST .../family"),
        c("TS-09-018", "Search", "q search matches mrn, name, phone, familyGroupCode", "P0", "Positive",
          "Patients exist.", "RECEPTIONIST",
          "q=Ramesh / q=UHID fragment / q=phone",
          "1. Search.",
          "Matching non-merged patients (max 80 API).",
          "GET /api/patients?q="),
        c("TS-09-019", "Search Phone", "phone≥8 digits expands family group members", "P0", "Positive",
          "Family group with P1 P2 P3.", "RECEPTIONIST",
          "phone=9876510001",
          "1. Search by phone.",
          "All family group members returned (phone search expand).",
          "GET /api/patients?phone="),
        c("TS-09-020", "Edit Front Desk", "Receptionist can edit demographics + clinical", "P0", "Positive",
          "P1 not merged.", "RECEPTIONIST",
          "address, allergies change",
          "1. /patients/[id]/edit → save.",
          "Updated. Audit PATIENT_UPDATED.",
          "PATCH /api/patients/[id]"),
        c("TS-09-021", "Edit Doctor", "Doctor can only patch clinical history fields", "P0", "RBAC",
          "P1.", "DOCTOR",
          "A) allergies update\nB) firstName update",
          "1. PATCH both.",
          "A succeeds. B ignored/forbidden for demographics.",
          "PATCH /api/patients/[id]"),
        c("TS-09-022", "Edit Access", "Edit page front desk only (nurse denied by default)", "P1", "RBAC",
          "nurseAsReceptionist false.", "NURSE",
          "/patients/[id]/edit",
          "1. Open.",
          "Denied / redirect to /patients.",
          "edit page"),
        c("TS-09-023", "Merge", "Merge duplicate into survivor moves clinical/billing rows", "P0", "Positive",
          "P1 survivor, force-registered duplicate. No dual active admissions.", "RECEPTIONIST",
          "merge duplicate → P1",
          "1. Merge on detail.",
          "Appointments/invoices/payments/records moved. advanceBalance summed. duplicate.mergedIntoId set. Family links on duplicate deleted. Audit PATIENT_MERGED.",
          "POST /api/patients/[survivor]/merge"),
        c("TS-09-024", "Merge Block", "Merge blocked if both have active admissions", "P0", "Negative",
          "Simulate both ADMITTED/DISCHARGE_ADVISED if wards enabled — OR skip if wards OOS: mark N/A.", "RECEPTIONIST",
          "both active admissions",
          "1. Merge.",
          "409. If wards out of scope and cannot setup: Skip with note.",
          "POST .../merge"),
        c("TS-09-025", "Merged Locked", "Cannot PATCH merged patient", "P0", "Negative",
          "Duplicate after merge.", "RECEPTIONIST",
          "PATCH merged id",
          "1. Edit merged.",
          "404.",
          "PATCH /api/patients/[id]"),
        c("TS-09-026", "Merged UI", "Detail shows merged banner; actions blocked", "P1", "Positive",
          "Merged patient.", "RECEPTIONIST",
          "Open merged detail",
          "1. View.",
          "Shows merged-into survivor. No merge/family actions.",
          "patients/[id]"),
        c("TS-09-027", "Merge Gap", "Document certificates/pharmacy orders not moved (watchlist)", "P2", "Positive",
          "If duplicate had certificate before merge.", "DOCTOR",
          "—",
          "1. After merge check certificate patientId.",
          "May still point to duplicate — record actual. Known gap.",
          "observation"),
        c("TS-09-028", "Insurance", "insuranceValidUntil invalid date rejected", "P2", "Negative",
          "—", "RECEPTIONIST",
          "insuranceValidUntil: not-a-date",
          "1. Save.",
          "Error.",
          "POST/PATCH patients"),
        c("TS-09-029", "Opt-in", "smsOptIn/whatsappOptIn default true", "P2", "Positive",
          "New patient.", "RECEPTIONIST",
          "defaults",
          "1. Create without toggling.",
          "Both true in DB/UI.",
          "POST /api/patients"),
        c("TS-09-030", "Phone Watchlist", "Non-Indian patient phone may be accepted (W-09)", "P1", "Boundary",
          "—", "RECEPTIONIST",
          "phone: 12345",
          "1. Register.",
          "Document actual — server may accept (unlike login). Log vs Watchlist W-09.",
          "POST /api/patients"),
        c("TS-09-031", "List Cap", "Page loads recent patients (server ~200)", "P2", "Positive",
          "Many patients.", "RECEPTIONIST",
          "/patients",
          "1. Open list.",
          "Loads; client filter works.",
          "/patients"),
        c("TS-09-032", "Family Self", "Cannot link patient to self", "P1", "Negative",
          "P1.", "RECEPTIONIST",
          "related=primary",
          "1. Link.",
          "Rejected.",
          "POST .../family"),
        c("TS-09-033", "Tenant", "Cannot read other hospital patient by id", "P0", "Security",
          "P6 in H4. Login H1 user.", "RECEPTIONIST",
          "GET /api/patients/{P6 id}",
          "1. Request.",
          "404/403. Not leaked.",
          "GET /api/patients/[id]"),
        c("TS-09-034", "Accountants", "ACCOUNTANT can view patient not edit demographics", "P1", "RBAC",
          "—", "ACCOUNTANT",
          "GET ok; PATCH demographics",
          "1. View.\n2. PATCH name.",
          "View ok. Demographics patch forbidden.",
          "patients API"),
        c("TS-09-035", "Emergency", "Emergency contact fields save", "P2", "Positive",
          "—", "RECEPTIONIST",
          "emergencyName + emergencyPhone",
          "1. Save.",
          "Persisted on detail.",
          "POST/PATCH"),
        c("TS-09-036", "Blood Group", "bloodGroup free text accepted", "P2", "Positive",
          "—", "RECEPTIONIST",
          "bloodGroup: B+",
          "1. Save.",
          "Stored.",
          "POST"),
        c("TS-09-037", "Relation Enum", "Family relations SPOUSE CHILD PARENT SIBLING OTHER", "P1", "Positive",
          "—", "RECEPTIONIST",
          "Each relation once",
          "1. Link with each.",
          "All accepted.",
          "POST .../family"),
        c("TS-09-038", "Directed Link", "Family link is directed (no auto reverse)", "P2", "Positive",
          "P1→P2 SPOUSE linked.", "RECEPTIONIST",
          "—",
          "1. Check P2 family list.",
          "Reverse link may be absent — document actual.",
          "UI detail"),
        c("TS-09-039", "Nurse Receptionist Off", "Nurse cannot register patient when toggle is off", "P0", "RBAC",
          "nurseAsReceptionist false. walkInByNurse false.", "NURSE",
          "/patients/new + POST /api/patients",
          "1. Open /patients/new.\n2. POST register.",
          "Page redirects. API 403. List still visible (clinical view).",
          "canRegisterPatient"),
        c("TS-09-040", "Nurse Receptionist On", "Nurse can register, edit, family-link, merge when toggle is on", "P0", "Positive",
          "nurseAsReceptionist true (TS-07-028). Unused patient data.", "NURSE",
          "New patient + edit address + family link",
          "1. Register patient.\n2. Edit demographics.\n3. Link family if second patient exists.",
          "All succeed like receptionist. Edit column appears on /patients list.",
          "POST/PATCH patients + family"),
        c("TS-09-041", "Nurse Receptionist On", "Second nurse can also register (not one designated nurse)", "P0", "Positive",
          "Toggle ON. U-H1-NUR2 exists (TS-06-036).", "NURSE (U-H1-NUR2)",
          "Another unused patient",
          "1. Login as second nurse.\n2. Register patient.",
          "Succeeds. Hospital-wide toggle — every nurse, not a single assignee.",
          "POST /api/patients"),
        c("TS-09-042", "Infant", "Unnamed infant registers as Baby of parent without a given name", "P0", "Positive",
          "Front desk. Parent name known. Extra sections stay collapsed.", "RECEPTIONIST",
          "unnamedInfant=true parentName='Ramesh Kumar' gender=MALE (DOB optional → today)",
          "1. Open /patients/new.\n2. Tick Unnamed infant / newborn.\n3. Enter parent name + gender (and parent mobile if known).\n4. Save without filling first name or extra sections.",
          "Created firstName='Baby of Ramesh Kumar', lastName empty, DOB today if omitted. Audit PATIENT_REGISTERED. List/detail show that name. Fast path — no photo/history/ID required.",
          "POST /api/patients unnamedInfant"),
        c("TS-09-043", "Infant", "Baby of name is easy to replace with the given name later", "P0", "Positive",
          "Infant from TS-09-042 exists.", "RECEPTIONIST",
          "PATCH firstName=Aarav lastName=Kumar",
          "1. Open Edit on the infant.\n2. Change Given name (banner explains Baby of).\n3. Save. Do not open extra sections.",
          "Name updates. UHID unchanged. Edit banner shown when firstName starts with Baby of.",
          "PATCH /api/patients/[id]"),
        c("TS-09-044", "Infant Family", "Unnamed infant under existing parent uses parent record name", "P0", "Positive",
          "Parent P1 on file with mobile.", "RECEPTIONIST",
          "Parent mobile + unnamedInfant + familyOf P1",
          "1. Enter parent mobile (family lookup appears).\n2. Tick unnamed infant.\n3. Save as child under P1.",
          "firstName=Baby of {P1 full name}. Inherits phone. PatientFamily CHILD. No 409 for shared phone. Same result from patient detail Add family member.",
          "POST /api/patients familyOf + unnamedInfant"),
    ]


def ts10_cases():
    return [
        c("TS-10-001", "Access", "Clinical view can open appointments list", "P0", "RBAC",
          "—", "RECEPTIONIST / DOCTOR / NURSE",
          "/appointments",
          "1. Open.",
          "List loads.",
          "/appointments"),
        c("TS-10-002", "Create Scheduled", "Front desk books SCHEDULED appointment", "P0", "Positive",
          "P1 + doctor + department. Doctor not on leave.", "RECEPTIONIST",
          "queueType SCHEDULED\nvisitType NEW\nreferral SELF\nscheduledAt tomorrow 10:00",
          "1. /appointments/new → save.",
          "Status SCHEDULED. Token assigned T-NNN. Token counter TOKEN-YYYY-MM-DD-doctorId. Notifies if applicable.",
          "POST /api/appointments"),
        c("TS-10-003", "Create Walk-in", "Walk-in auto CHECKED_IN + checkInAt", "P0", "Positive",
          "Same fixtures today.", "RECEPTIONIST",
          "queueType WALK_IN",
          "1. Create walk-in.",
          "Status CHECKED_IN. Token set. Redirect often to /billing/collect/{id}. Nurses notified arrived.",
          "POST /api/appointments"),
        c("TS-10-004", "Doctor Walk-in", "Doctor creates walk-in for self when policy allows", "P0", "Positive",
          "walkInByDoctor true.", "DOCTOR",
          "WALK_IN",
          "1. Create.",
          "Doctor auto-assigned self. WALK_IN only for non-front-desk.",
          "POST /api/appointments"),
        c("TS-10-005", "Validation", "patientId departmentId doctorId required", "P0", "Negative",
          "—", "RECEPTIONIST",
          "Omit doctor",
          "1. Submit.",
          "400/error — doctor must resolve to active doctor with appUserId.",
          "POST /api/appointments"),
        c("TS-10-006", "Merged Patient", "Cannot book for merged patient", "P0", "Negative",
          "Merged duplicate id.", "RECEPTIONIST",
          "patientId=merged",
          "1. Book.",
          "Rejected.",
          "POST /api/appointments"),
        c("TS-10-007", "Leave", "Doctor on leave → 409", "P0", "Negative",
          "Approved/pending leave today.", "RECEPTIONIST",
          "that doctor + today",
          "1. Book.",
          "409 on leave.",
          "POST /api/appointments"),
        c("TS-10-008", "No Slot Conflict", "Two appointments same doctor same time allowed", "P1", "Positive",
          "—", "RECEPTIONIST",
          "Same scheduledAt twice",
          "1. Create two.",
          "Both succeed (no conflict engine). Document as by-design.",
          "POST /api/appointments"),
        c("TS-10-009", "Visit Types", "NEW FOLLOW_UP EMERGENCY accepted", "P1", "Positive",
          "—", "RECEPTIONIST",
          "Each visitType",
          "1. Create three.",
          "All stored. Fee behavior for FOLLOW_UP covered in collect/TS-14.",
          "POST /api/appointments"),
        c("TS-10-010", "checkInNow", "Scheduled with checkInNow → CHECKED_IN", "P1", "Positive",
          "—", "RECEPTIONIST",
          "SCHEDULED + checkInNow",
          "1. Create.",
          "CHECKED_IN immediately.",
          "POST /api/appointments"),
        c("TS-10-011", "Check-in", "Front desk checkin from SCHEDULED", "P0", "Positive",
          "SCHEDULED appt.", "RECEPTIONIST",
          "action checkin",
          "1. Check in.",
          "CHECKED_IN. Token if missing. checkInAt set. Nurse notify if no vitals.",
          "PATCH /api/appointments/[id]"),
        c("TS-10-012", "Start", "Owning doctor starts from CHECKED_IN → IN_PROGRESS", "P0", "Positive",
          "CHECKED_IN for doctor.", "DOCTOR",
          "action start",
          "1. Start consult.",
          "IN_PROGRESS. checkInAt if missing.",
          "PATCH action=start"),
        c("TS-10-013", "Start RBAC", "Receptionist cannot start (W-01)", "P0", "RBAC",
          "CHECKED_IN.", "RECEPTIONIST",
          "action start",
          "1. Start.",
          "403 doctorOwnsVisit. Record Watchlist W-01.",
          "PATCH action=start"),
        c("TS-10-014", "Start Ownership", "Other doctor cannot start", "P0", "RBAC",
          "Appt for Doc A.", "DOCTOR B",
          "start",
          "1. Start.",
          "403.",
          "PATCH"),
        c("TS-10-015", "SUPER Start", "SUPER_ADMIN can start any", "P1", "Positive",
          "CHECKED_IN.", "SUPER_ADMIN",
          "start",
          "1. Start.",
          "IN_PROGRESS.",
          "PATCH"),
        c("TS-10-016", "Complete Gate", "complete without APPROVED assessment → 409", "P0", "Negative",
          "IN_PROGRESS no assessment approve.", "DOCTOR",
          "action complete",
          "1. Complete.",
          "409 needs approved assessment.",
          "PATCH complete"),
        c("TS-10-017", "Complete", "complete after APPROVED → COMPLETED", "P0", "Positive",
          "Assessment APPROVED (TS-12).", "DOCTOR",
          "complete",
          "1. Complete.",
          "COMPLETED + checkOutAt.",
          "PATCH complete"),
        c("TS-10-018", "Checkout", "checkout completes WITHOUT approved assessment (W-02)", "P0", "Positive",
          "IN_PROGRESS draft assessment.", "RECEPTIONIST",
          "action checkout",
          "1. Checkout.",
          "COMPLETED succeeds. Document W-02.",
          "PATCH checkout"),
        c("TS-10-019", "Cancel", "Front desk cancel → CANCELLED", "P0", "Positive",
          "SCHEDULED appt.", "RECEPTIONIST",
          "cancel",
          "1. Cancel.",
          "CANCELLED + cancelledAt.",
          "PATCH cancel"),
        c("TS-10-020", "NoShow", "noshow from SCHEDULED", "P0", "Positive",
          "SCHEDULED.", "RECEPTIONIST",
          "noshow",
          "1. Mark no-show.",
          "NO_SHOW.",
          "PATCH noshow"),
        c("TS-10-021", "NoShow Any", "noshow from IN_PROGRESS allowed (W-03)", "P1", "Positive",
          "IN_PROGRESS.", "RECEPTIONIST",
          "noshow",
          "1. Mark.",
          "NO_SHOW. Document W-03.",
          "PATCH noshow"),
        c("TS-10-022", "Reschedule", "Reschedule updates time; NO_SHOW→SCHEDULED", "P0", "Positive",
          "NO_SHOW appt. Doctor free on new date.", "RECEPTIONIST",
          "new scheduledAt",
          "1. Reschedule.",
          "scheduledAt updated. Status SCHEDULED. Token not renumbered.",
          "PATCH reschedule"),
        c("TS-10-023", "Reschedule Block", "Cannot reschedule CANCELLED/COMPLETED", "P1", "Negative",
          "COMPLETED.", "RECEPTIONIST",
          "reschedule",
          "1. Attempt.",
          "Blocked.",
          "PATCH reschedule"),
        c("TS-10-024", "Reschedule Leave", "Reschedule onto leave day → 409", "P1", "Negative",
          "Doctor leave on target day.", "RECEPTIONIST",
          "—",
          "1. Reschedule.",
          "409.",
          "PATCH reschedule"),
        c("TS-10-025", "Remind", "Remind queues message when phone ≥10 digits", "P1", "Positive",
          "SCHEDULED + patient phone.", "RECEPTIONIST",
          "action remind",
          "1. Send reminder.",
          "Outbound/AppointmentReminder created (SMS/WA/email per config).",
          "PATCH remind"),
        c("TS-10-026", "Remind Phone", "Remind fails if phone short", "P1", "Negative",
          "Patient phone <10 digits.", "RECEPTIONIST",
          "remind",
          "1. Remind.",
          "Error about phone.",
          "PATCH remind"),
        c("TS-10-027", "Photo", "Front desk sets visit photo; copies to patient if empty", "P2", "Positive",
          "Patient without photo.", "RECEPTIONIST",
          "action photo valid image",
          "1. Upload.",
          "Visit photo set; patient photo filled if was empty.",
          "PATCH photo"),
        c("TS-10-028", "Queue", "Queue page orders by token then scheduledAt", "P0", "Positive",
          "Several today appts.", "RECEPTIONIST",
          "/queue",
          "1. Open queue for today.",
          "Ordered token asc. Doctor filter for DOCTOR role.",
          "/queue"),
        c("TS-10-029", "Nurse Page", "Nurse station only NURSE_VITALS_ROLES", "P0", "RBAC",
          "—", "DOCTOR / NURSE",
          "/nurse",
          "1. Open as doctor and nurse.",
          "Doctor denied; nurse ok.",
          "/nurse"),
        c("TS-10-030", "Fee Follow-up", "FOLLOW_UP uses followUpFee if >0 else full fee chain", "P0", "Positive",
          "Doctor followUpFee=200; consultationFee=500.", "RECEPTIONIST",
          "visitType FOLLOW_UP → collect page",
          "1. Create + open collect.",
          "Due ₹200. If followUpFee=0 → falls through to 500 (W-10).",
          "consultationFeeForVisit"),
        c("TS-10-031", "Default Fee", "All fees zero → DEFAULT_OPD_FEE 500", "P1", "Positive",
          "Doctor/hospital/dept fees 0.", "RECEPTIONIST",
          "collect",
          "1. Open collect.",
          "₹500.",
          "fees.ts"),
        c("TS-10-032", "Token Display", "Token displays as T-NNN", "P1", "Positive",
          "Appt with token 7.", "RECEPTIONIST",
          "—",
          "1. View queue/detail.",
          "Shows T-007 style.",
          "display.ts"),
        c("TS-10-033", "Cancel Terminal", "Cannot checkin CANCELLED", "P1", "Negative",
          "CANCELLED.", "RECEPTIONIST",
          "checkin",
          "1. Checkin.",
          "Blocked.",
          "PATCH"),
        c("TS-10-034", "Start From Scheduled", "Doctor can start from SCHEDULED (skips explicit checkin)", "P1", "Positive",
          "SCHEDULED today.", "DOCTOR (owner)",
          "start",
          "1. Start.",
          "IN_PROGRESS allowed from SCHEDULED.",
          "PATCH start"),
        c("TS-10-035", "Referral", "referralSource DOCTOR + referredBy text", "P2", "Positive",
          "—", "RECEPTIONIST",
          "referralSource DOCTOR referredBy Dr X",
          "1. Create.",
          "Stored.",
          "POST"),
        c("TS-10-036", "Collect Block", "Cannot collect for CANCELLED/NO_SHOW", "P0", "Negative",
          "NO_SHOW appt.", "RECEPTIONIST",
          "/billing/collect/id",
          "1. Collect payment.",
          "409 blocked.",
          "POST .../collect"),
        c("TS-10-037", "Detail Access", "Clinical roles open visit detail", "P1", "Positive",
          "Appt exists.", "NURSE",
          "/appointments/[id]",
          "1. Open.",
          "Detail shows; panels by role.",
          "detail page"),
        c("TS-10-038", "Past Booking", "Past scheduledAt not explicitly blocked", "P2", "Positive",
          "—", "RECEPTIONIST",
          "scheduledAt yesterday",
          "1. Create.",
          "Allowed — document by-design.",
          "POST"),
        c("TS-10-039", "Nurse Walk-in Policy Off", "Nurse walk-in denied when walkInByNurse false and receptionist toggle off", "P1", "Negative",
          "walkInByNurse false. nurseAsReceptionist false.", "NURSE",
          "WALK_IN",
          "1. Create.",
          "Denied.",
          "POST"),
        c("TS-10-040", "Encounter No", "Visit summary encounter uses hospitalCode+date+token", "P2", "Positive",
          "Approved visit with token.", "DOCTOR",
          "Open summary PDF (TS-12)",
          "1. Check encounter number.",
          "Format {code}{YYYYMMDD}{token4} or without token.",
          "visit-summary"),
        c("TS-10-041", "Photo Patient", "Visit photo does not overwrite existing patient photo", "P2", "Positive",
          "Patient already has photo.", "RECEPTIONIST",
          "New visit photo",
          "1. Set visit photo.",
          "Patient photo unchanged.",
          "PATCH photo"),
        c("TS-10-042", "Audit", "Appointment status changes audited where implemented", "P2", "Positive",
          "After checkin/cancel.", "SUPER_ADMIN",
          "audit log",
          "1. Review.",
          "Relevant appointment audits present.",
          "audit-log"),
        c("TS-10-043", "Availability", "Booking form shows slot list when doctor has windows", "P0", "Positive",
          "Doctor D1 has Mon 10:00–12:00 and 14:00–16:00.", "RECEPTIONIST",
          "Date = next Monday",
          "1. /appointments/new → select D1 → pick Monday.\n2. Open Available time.",
          "Dropdown shows 15-min slots inside windows only (not 13:00).",
          "GET /api/appointments/availability"),
        c("TS-10-044", "Availability", "Cannot book outside configured windows", "P0", "Negative",
          "Doctor D1 Mon 10:00–12:00 only.", "RECEPTIONIST",
          "scheduledAt Monday 15:00",
          "1. POST appointment outside window (API or UI).",
          "400 Chosen time is outside the doctor's availability.",
          "POST /api/appointments"),
        c("TS-10-045", "Availability", "Book inside window succeeds", "P0", "Positive",
          "Doctor D1 Mon 10:00–12:00.", "RECEPTIONIST",
          "Monday 10:30",
          "1. Book scheduled appointment.",
          "201 SCHEDULED. Token issued.",
          "POST /api/appointments"),
        c("TS-10-046", "Availability", "Day with no windows shows empty slots / cannot book", "P1", "Negative",
          "Doctor D1 only Monday windows.", "RECEPTIONIST",
          "Date = Tuesday",
          "1. Select D1 + Tuesday.",
          "No slots / message no availability. POST 400 if forced.",
          "availability + POST"),
        c("TS-10-047", "Availability", "No windows configured — free-form time still allowed", "P1", "Positive",
          "Doctor D2 has zero StaffAvailabilityWindow rows.", "RECEPTIONIST",
          "Any datetime-local",
          "1. Book any future time.",
          "Allowed (legacy). UI shows free time input.",
          "POST /api/appointments"),
        c("TS-10-048", "Availability", "Reschedule outside window rejected", "P0", "Negative",
          "Appt for D1 inside window. D1 Mon 10–12 only.", "RECEPTIONIST",
          "Reschedule to Monday 15:00",
          "1. action=reschedule.",
          "400 outside availability.",
          "PATCH appointments/[id]"),
        c("TS-10-049", "Availability", "Weekdays schedule offers slots Mon–Fri only", "P0", "Positive",
          "Doctor D1 saved Weekdays 10:00–13:00.", "RECEPTIONIST",
          "Next Wednesday and next Saturday",
          "1. Select D1 + Wednesday → slots 10:00–12:45.\n2. Select D1 + Saturday.",
          "Wednesday has slots. Saturday has no slots / cannot book.",
          "GET /api/appointments/availability"),
        c("TS-10-050", "Availability", "Weekend schedule offers slots Sat–Sun only", "P0", "Positive",
          "Doctor D1 saved Weekend 10:00–12:00.", "RECEPTIONIST",
          "Next Saturday and next Monday",
          "1. Book Saturday 10:30 (ok).\n2. Attempt Monday 10:30.",
          "Saturday succeeds. Monday 400 / no slots.",
          "availability + POST"),
        c("TS-10-051", "Availability", "Everyday schedule offers slots any day of week", "P0", "Positive",
          "Doctor D1 saved Everyday 09:00–17:00.", "RECEPTIONIST",
          "Next Sunday and next Wednesday",
          "1. Check slots both days inside 09–17.",
          "Both days show slots. Book either succeeds.",
          "GET availability + POST"),
        c("TS-10-052", "Availability", "Switching doctor reloads that doctor's slots only", "P0", "Positive",
          "D1 Weekdays 10–13; D2 Weekend 10–12.", "RECEPTIONIST",
          "Date = next Saturday",
          "1. Select D1 + Saturday → no slots.\n2. Switch to D2 + same Saturday.",
          "D2 shows weekend slots. Times never mix across doctors.",
          "GET /api/appointments/availability?doctorId="),
        c("TS-10-053", "Nurse Front Desk Off", "Nurse cannot cancel/reschedule/check-in when toggle is off", "P0", "RBAC",
          "nurseAsReceptionist false. SCHEDULED visit exists.", "NURSE",
          "cancel / reschedule / checkin",
          "1. Attempt each front-desk action.",
          "403. Nurse station / vitals still allowed (TS-11).",
          "appointments status/reschedule"),
        c("TS-10-054", "Nurse Front Desk On", "Nurse can book, walk-in, check-in, cancel, reschedule when toggle is on", "P0", "Positive",
          "nurseAsReceptionist true. Patient + doctor available.", "NURSE",
          "SCHEDULED then WALK_IN",
          "1. Book scheduled.\n2. Walk-in.\n3. Check-in scheduled.\n4. Cancel one visit.\n5. Reschedule another.",
          "All succeed like receptionist. Nurse still cannot start consult (W-01 / doctorOwnsVisit).",
          "POST appointments + status"),
        c("TS-10-055", "Nurse Front Desk On", "Nurse nav shows billing + nurse station", "P1", "Positive",
          "Toggle ON. Refresh session after settings save.", "NURSE",
          "App shell nav",
          "1. Sign in as nurse (or hard refresh).\n2. Inspect sidebar.",
          "Nurse station still listed. Billing, collections, reports visible (module flags permitting). Dedicated receptionist nav unchanged.",
          "app-shell.tsx"),
        c("TS-10-056", "Nurse Front Desk Off", "Turning toggle off hides nurse billing nav and blocks manage", "P1", "Positive",
          "After TS-10-054. Superadmin sets nurseAsReceptionist false.", "NURSE",
          "—",
          "1. Save toggle off.\n2. Refresh nurse session.\n3. Retry cancel.",
          "Billing nav gone. Cancel/reschedule 403 again. Existing visits unchanged.",
          "nav + APIs"),
    ]


def ts11_cases():
    return [
        c("TS-11-001", "Access", "Only NURSE can record vitals", "P0", "RBAC",
          "Today CHECKED_IN appt.", "DOCTOR / NURSE / SUPER_ADMIN",
          "POST vitals",
          "1. Nurse saves.\n2. Doctor attempts.\n3. Admin (any view) attempts.",
          "Nurse 200. Doctor and SUPER_ADMIN 403.",
          "POST /api/appointments/[id]/vitals"),
        c("TS-11-002", "Happy", "Required vitals height weight temperature save + BMI", "P0", "Positive",
          "Today eligible visit.", "NURSE",
          "heightCm 170\nweightKg 70\ntemperatureC 36.8",
          "1. Save from nurse station or visit.",
          "Upsert VisitVitals. BMI ≈ 24.2 (1 decimal). Audit VITALS_RECORDED. Doctor notified on first save.",
          "POST vitals"),
        c("TS-11-003", "Update", "Second save audits VITALS_UPDATED", "P1", "Positive",
          "Vitals exist.", "NURSE",
          "weightKg 71",
          "1. Update.",
          "Updated. VITALS_UPDATED.",
          "POST vitals"),
        c("TS-11-004", "Fever", "hasFever defaults true when temp≥38", "P0", "Positive",
          "—", "NURSE",
          "temperatureC 38.5",
          "1. Save without overriding hasFever.",
          "hasFever true (unless body overrides).",
          "POST vitals"),
        c("TS-11-005", "Ranges Height", "heightCm boundaries 40–250", "P0", "Boundary",
          "—", "NURSE",
          "A) 39 B) 40 C) 250 D) 251",
          "1. Each.",
          "A/D fail. B/C ok.",
          "POST vitals"),
        c("TS-11-006", "Ranges Weight", "weightKg 2–400", "P0", "Boundary",
          "—", "NURSE",
          "1.9 / 2 / 400 / 401",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-007", "Ranges Temp", "temperatureC 30–45", "P0", "Boundary",
          "—", "NURSE",
          "29.9 / 30 / 45 / 45.1",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-008", "Optional SpO2", "spo2Percent 50–100", "P1", "Boundary",
          "Required fields ok.", "NURSE",
          "49 / 50 / 100 / 101",
          "1. Each.",
          "Outside fail; valid stored as int.",
          "POST vitals"),
        c("TS-11-009", "Optional Pulse", "pulseBpm 30–220", "P1", "Boundary",
          "—", "NURSE",
          "29 / 30 / 220 / 221",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-010", "Optional RR", "respiratoryRate 6–60", "P1", "Boundary",
          "—", "NURSE",
          "5 / 6 / 60 / 61",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-011", "BP Sys", "bpSystolic 60–260", "P1", "Boundary",
          "—", "NURSE",
          "59 / 60 / 260 / 261",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-012", "BP Dia", "bpDiastolic 30–160", "P1", "Boundary",
          "—", "NURSE",
          "29 / 30 / 160 / 161",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-013", "Sugar", "bloodSugarMgDl 20–800", "P1", "Boundary",
          "—", "NURSE",
          "19 / 20 / 800 / 801",
          "1. Each.",
          "Outside fail.",
          "POST vitals"),
        c("TS-11-014", "Ideal Ranges", "Ideal range warnings do not block save", "P2", "Positive",
          "—", "NURSE",
          "pulse 50 (below ideal 60–100) but in hard range",
          "1. Save.",
          "UI may warn; save succeeds.",
          "POST vitals"),
        c("TS-11-015", "Same Day Lock", "Cannot record vitals for yesterday visit", "P0", "Negative",
          "Yesterday CHECKED_IN/IN_PROGRESS.", "NURSE",
          "—",
          "1. Save vitals.",
          "Rejected — canNurseRecordVitals same calendar day only.",
          "POST vitals"),
        c("TS-11-016", "Cancelled", "No vitals for CANCELLED/NO_SHOW", "P1", "Negative",
          "CANCELLED today.", "NURSE",
          "—",
          "1. Save.",
          "Rejected.",
          "POST vitals"),
        c("TS-11-017", "Nurse Station", "Eligible visits appear on /nurse for today", "P0", "Positive",
          "Today checked-in without vitals.", "NURSE",
          "/nurse",
          "1. Open.",
          "Visit listed; can record.",
          "/nurse"),
        c("TS-11-018", "Notes", "Optional notes stored", "P2", "Positive",
          "—", "NURSE",
          "notes: Patient anxious",
          "1. Save.",
          "Notes persisted.",
          "POST vitals"),
        c("TS-11-019", "Override Fever", "Explicit hasFever false with high temp", "P2", "Positive",
          "—", "NURSE",
          "temp 38.5 hasFever false",
          "1. Save if UI/API allows override.",
          "hasFever false stored.",
          "POST vitals"),
        c("TS-11-020", "SUPER_ADMIN", "Super admin cannot record vitals", "P0", "Negative",
          "Today visit.", "SUPER_ADMIN",
          "valid vitals",
          "1. Save from Admin or Doctor view.",
          "403. Only NURSE records vitals.",
          "POST vitals"),
        c("TS-11-021", "One Row", "One vitals row per appointment (upsert)", "P1", "Positive",
          "—", "NURSE",
          "Save twice",
          "1. Two saves.",
          "Still single VisitVitals row.",
          "DB/UI"),
        c("TS-11-022", "Required Missing", "Missing height/weight/temp fails", "P0", "Negative",
          "—", "NURSE",
          "Omit weight",
          "1. Save.",
          "400.",
          "POST vitals"),
        c("TS-11-023", "Display", "Vitals show on visit detail for clinical roles", "P1", "Positive",
          "Vitals saved.", "DOCTOR",
          "visit detail",
          "1. Open appointment.",
          "Vitals visible including BMI.",
          "/appointments/[id]"),
        c("TS-11-024", "Notify", "First vitals notifies doctor once", "P1", "Positive",
          "Doctor has notifications.", "NURSE",
          "First save",
          "1. Save.\n2. Check doctor notifications.",
          "Notification created.",
          "notifications"),
        c("TS-11-025", "Tenant", "Cannot post vitals to other hospital appointment", "P0", "Security",
          "H4 appointment id.", "NURSE H1",
          "—",
          "1. POST.",
          "404/403.",
          "POST vitals"),
        c("TS-11-026", "Float BMI", "BMI calculation weight/(height/100)^2 one decimal", "P1", "Positive",
          "—", "NURSE",
          "h=165 w=60 → BMI 22.0",
          "1. Save.\n2. Verify BMI.",
          "Matches formula rounded 1 decimal.",
          "POST vitals"),
    ]


def ts12_cases():
    return [
        c("TS-12-001", "Access", "Only Doctor view can save assessment", "P0", "RBAC",
          "IN_PROGRESS own visit.", "NURSE / DOCTOR / SUPER_ADMIN",
          "POST assessment",
          "1. Nurse attempt.\n2. Doctor save.\n3. Admin in Admin view attempt.\n4. Admin-as-doctor in Doctor view save own visit.",
          "Nurse and Admin view 403. Doctor / Doctor view ok.",
          "POST .../assessment"),
        c("TS-12-002", "Ownership", "Doctor cannot assess another doctor's visit", "P0", "RBAC",
          "Visit owned by Doc A.", "DOCTOR B",
          "save",
          "1. Save.",
          "403.",
          "POST assessment"),
        c("TS-12-003", "Draft", "Save assessment as DRAFT", "P0", "Positive",
          "Own IN_PROGRESS.", "DOCTOR",
          "chiefComplaint, examination, diagnosis draft text",
          "1. Save (no approve).",
          "VisitAssessment DRAFT. Fields trimmed.",
          "POST assessment"),
        c("TS-12-004", "Approve", "Approve requires diagnosis", "P0", "Negative",
          "Draft without diagnosis.", "DOCTOR",
          "action approve",
          "1. Approve.",
          "Error — diagnosis required.",
          "POST approve"),
        c("TS-12-005", "Approve", "Approve with diagnosis → APPROVED + signature snapshot", "P0", "Positive",
          "Policy signature optional OR doctor has ACTIVE signature.", "DOCTOR",
          "diagnosis: Viral fever\naction approve",
          "1. Approve.",
          "APPROVED + approvedAt/by. Signature snapshot if present. Pharmacy Rx sync from prescription text. Notifications. Audit.",
          "POST approve"),
        c("TS-12-006", "Signature Gate", "Approve blocked when requireSignatureForApproval and no ACTIVE sig", "P0", "Negative",
          "Policy ON. No signature.", "DOCTOR",
          "approve with diagnosis",
          "1. Approve.",
          "Blocked.",
          "POST approve"),
        c("TS-12-007", "Republish", "Save after approve keeps APPROVED", "P1", "Positive",
          "Already APPROVED.", "DOCTOR",
          "Edit advice + save",
          "1. Save.",
          "Still APPROVED. May audit VISIT_SUMMARY_REPUBLISHED.",
          "POST assessment"),
        c("TS-12-008", "Outcome", "visitOutcome FOLLOW_UP or DISCHARGE", "P1", "Positive",
          "—", "DOCTOR",
          "visitOutcome FOLLOW_UP + followUpAt",
          "1. Save.",
          "Stored. Invalid outcome → null.",
          "POST assessment"),
        c("TS-12-009", "Follow-up Date", "followUp action updates date; leave check", "P1", "Positive",
          "Existing assessment. Doctor free that day.", "DOCTOR",
          "action followup",
          "1. Set follow-up.",
          "followUpAt updated. Leave day rejected.",
          "POST followup"),
        c("TS-12-010", "Prescription Text", "Prescription plain text lines parse on approve", "P0", "Positive",
          "—", "DOCTOR",
          "Rx lines: Paracetamol 500 || 1-0-1\nAmoxicillin | 5 days",
          "1. Approve with prescription.",
          "Text stored. Pharmacy Rx lines created/updated from parse (module may be disabled — still sync attempt).",
          "syncPharmacyRxFromAssessment"),
        c("TS-12-011", "Medicine Suggest", "Suggest requires q≥2 chars", "P0", "Positive",
          "Logged in.", "DOCTOR",
          "q=pa limit=12",
          "1. Type in Rx suggest.",
          "Returns catalog hits {id,name,salt,pack,manufacturer}. q=a alone empty/fail.",
          "GET /api/medicines/suggest"),
        c("TS-12-012", "Lab Picks", "lab-tests action upserts investigation picks", "P1", "Positive",
          "Lab module may be off — if off, Skip.\nElse pick tests.", "DOCTOR",
          "action lab-tests",
          "1. Add investigations.",
          "Lab order upserted. If lab OOS Skip.",
          "POST lab-tests"),
        c("TS-12-013", "Summary Send", "Send visit summary WhatsApp requires APPROVED + phone", "P0", "Positive",
          "APPROVED. Patient phone ≥10. WhatsApp optional.", "DOCTOR",
          "POST summary/send",
          "1. Send.",
          "PDF built. OutboundMessage. If no WhatsApp provider: console/dummy still records attempt per env.",
          "POST .../summary/send"),
        c("TS-12-014", "Summary Send Gate", "Cannot send summary if not APPROVED", "P0", "Negative",
          "DRAFT only.", "DOCTOR",
          "send",
          "1. Send.",
          "Rejected.",
          "POST summary/send"),
        c("TS-12-015", "Summary Roles", "PRINT_SUMMARY_ROLES can send", "P1", "RBAC",
          "APPROVED.", "NURSE / RECEPTIONIST / PHARMACIST",
          "send",
          "1. Nurse/Recep send.\n2. Pharmacist if exists.",
          "Nurse/Recep allowed. Pharmacist 403.",
          "POST summary/send"),
        c("TS-12-016", "Investigations Send", "Send investigation list PDF when items exist", "P1", "Positive",
          "≥1 non-cancelled lab item. If lab OOS Skip.", "DOCTOR",
          "investigations/send",
          "1. Send.",
          "WhatsApp PDF. Skip if no lab.",
          "POST .../investigations/send"),
        c("TS-12-017", "PDF Content", "Visit summary PDF contains identity diagnosis vitals Rx", "P0", "Positive",
          "APPROVED with vitals+Rx.", "DOCTOR",
          "Print/download summary",
          "1. Open PDF.",
          "Has hospital letterhead, UHID, encounter no, diagnosis, vitals, Rx table, signature if any. Starts with %PDF.",
          "visit-summary-pdf"),
        c("TS-12-018", "Fields", "All assessment text fields save", "P1", "Positive",
          "—", "DOCTOR",
          "chiefComplaint examination diagnosis summary prescription advice",
          "1. Save all.",
          "All persisted.",
          "POST assessment"),
        c("TS-12-019", "Empty Rx Approve", "Approve with empty prescription cancels awaiting pharmacy Rx if any", "P2", "Positive",
          "Prior approve had Rx; pharmacy module on — else Skip.", "DOCTOR",
          "Clear Rx + approve again",
          "1. Approve.",
          "Awaiting pharmacy order cancelled if coded.",
          "syncPharmacyRx"),
        c("TS-12-020", "SUPER_ADMIN", "Admin assesses only in Doctor view on own visits", "P0", "RBAC",
          "Admin linked as doctor; own IN_PROGRESS visit.", "SUPER_ADMIN",
          "A) Admin view save\nB) Doctor view save own visit\nC) Doctor view save another doctor's visit",
          "1. Attempt A–C.",
          "A 403 switch to Doctor view. B ok. C 403 own consults only.",
          "POST assessment"),
        c("TS-12-021", "Phone Send", "summary send fails if phone <10 digits", "P1", "Negative",
          "APPROVED. Short phone.", "DOCTOR",
          "send",
          "1. Send.",
          "400 phone.",
          "POST summary/send"),
        c("TS-12-022", "Channel", "SMS channel maps to WhatsApp for summary send", "P2", "Positive",
          "APPROVED.", "DOCTOR",
          "channel SMS if UI offers",
          "1. Send as SMS.",
          "Treated as WhatsApp per normalizeWhatsAppChannel.",
          "POST summary/send"),
        c("TS-12-023", "Complete Link", "After approve, complete visit succeeds", "P0", "Positive",
          "APPROVED.", "DOCTOR",
          "complete",
          "1. Complete.",
          "COMPLETED. Cross-check TS-10-017.",
          "PATCH complete"),
        c("TS-12-024", "Tenant", "Cannot assess other hospital appointment", "P0", "Security",
          "H4 appt.", "DOCTOR H1",
          "—",
          "1. POST.",
          "404/403.",
          "POST assessment"),
        c("TS-12-025", "Advice", "Long advice text accepted", "P2", "Positive",
          "—", "DOCTOR",
          "Long advice paragraph",
          "1. Save.",
          "Stored trimmed.",
          "POST"),
        c("TS-12-026", "Diagnosis Case", "Whitespace-only diagnosis fails approve", "P1", "Boundary",
          "—", "DOCTOR",
          "diagnosis: '   '",
          "1. Approve.",
          "Fails required diagnosis.",
          "POST approve"),
        c("TS-12-027", "Suggest Limit", "limit clamped 1–20", "P2", "Boundary",
          "—", "DOCTOR",
          "limit=100",
          "1. Suggest.",
          "Returns ≤20.",
          "GET suggest"),
        c("TS-12-028", "UI Panels", "Visit page shows assessment panel for doctor", "P1", "Positive",
          "Own visit.", "DOCTOR",
          "/appointments/[id]",
          "1. Open.",
          "Assessment editor visible.",
          "UI"),
        c("TS-12-029", "Nurse View", "Nurse can view but not approve", "P1", "RBAC",
          "Draft exists.", "NURSE",
          "Open visit",
          "1. View.\n2. Approve API.",
          "View ok. Approve 403.",
          "UI + API"),
        c("TS-12-030", "Audit", "Assessment approve in audit", "P2", "Positive",
          "After approve.", "SUPER_ADMIN",
          "audit",
          "1. Check.",
          "Assessment/summary audit entries present.",
          "audit-log"),
        c("TS-12-031", "followUpAt only", "followup action requires existing assessment", "P1", "Negative",
          "No assessment yet.", "DOCTOR",
          "action followup",
          "1. Set follow-up.",
          "Error — assessment missing.",
          "POST followup"),
        c("TS-12-032", "Discontinued Drugs", "Suggest excludes discontinued catalog items", "P2", "Positive",
          "If catalog has discontinued flag.", "DOCTOR",
          "q matching discontinued",
          "1. Suggest.",
          "Discontinued not returned.",
          "GET suggest"),
    ]


def ts13_cases():
    return [
        c("TS-13-001", "Access", "Only DOCTOR/SUPER_ADMIN issue certificates", "P0", "RBAC",
          "—", "RECEPTIONIST / DOCTOR",
          "/certificates/new",
          "1. Open/create as each.",
          "Receptionist denied. Doctor allowed.",
          "POST /api/certificates"),
        c("TS-13-002", "Sick Leave", "Issue SICK_LEAVE with restFrom/restTo", "P0", "Positive",
          "Patient P1. Signature ok if policy on.", "DOCTOR",
          "type SICK_LEAVE\ndiagnosis: Viral fever\nrestFrom today\nrestTo +3 days",
          "1. Issue.",
          "certificateNo MC-{CODE}-NNNNN. Status ISSUED. Audit MEDICAL_CERTIFICATE_ISSUED.",
          "POST /api/certificates"),
        c("TS-13-003", "Sick Leave Val", "restTo before restFrom rejected", "P0", "Negative",
          "—", "DOCTOR",
          "restTo < restFrom",
          "1. Issue.",
          "400 end ≥ start.",
          "POST certificates"),
        c("TS-13-004", "Sick Leave Val", "Missing rest dates rejected", "P0", "Negative",
          "—", "DOCTOR",
          "SICK_LEAVE diagnosis only",
          "1. Issue.",
          "400 restFrom/restTo required.",
          "POST"),
        c("TS-13-005", "Fitness", "Issue FITNESS with fitFor enum", "P0", "Positive",
          "—", "DOCTOR",
          "type FITNESS\nfitFor WORK|SCHOOL|SPORTS|TRAVEL\ndiagnosis ok",
          "1. Issue FITNESS WORK.",
          "ISSUED. fitFor stored.",
          "POST"),
        c("TS-13-006", "Fitness Val", "FITNESS without fitFor rejected", "P0", "Negative",
          "—", "DOCTOR",
          "FITNESS no fitFor",
          "1. Issue.",
          "400.",
          "POST"),
        c("TS-13-007", "General", "Issue GENERAL with purpose", "P0", "Positive",
          "—", "DOCTOR",
          "type GENERAL\npurpose: Travel\ndiagnosis",
          "1. Issue.",
          "ISSUED.",
          "POST"),
        c("TS-13-008", "General Val", "GENERAL without purpose rejected", "P0", "Negative",
          "—", "DOCTOR",
          "no purpose",
          "1. Issue.",
          "400.",
          "POST"),
        c("TS-13-009", "Diagnosis", "diagnosis always required", "P0", "Negative",
          "—", "DOCTOR",
          "empty diagnosis",
          "1. Issue any type.",
          "400.",
          "POST"),
        c("TS-13-010", "Merged", "Cannot issue for merged patient", "P0", "Negative",
          "Merged patient id.", "DOCTOR",
          "—",
          "1. Issue.",
          "Rejected.",
          "POST"),
        c("TS-13-011", "Appointment Link", "Optional appointmentId must belong to patient", "P1", "Negative",
          "Appt of other patient.", "DOCTOR",
          "wrong appointmentId",
          "1. Issue.",
          "Rejected.",
          "POST"),
        c("TS-13-012", "Signature Gate", "Issue blocked when signature required and missing", "P0", "Negative",
          "Policy ON. No ACTIVE sig.", "DOCTOR",
          "valid sick leave fields",
          "1. Issue.",
          "Blocked.",
          "POST"),
        c("TS-13-013", "Void Own", "Issuer doctor can void own certificate", "P0", "Positive",
          "ISSUED by this doctor.", "DOCTOR",
          "voidReason: Typo",
          "1. Void.",
          "VOIDED + voidedAt/by. PDF shows Voided banner.",
          "POST .../void"),
        c("TS-13-014", "Void Other", "Non-issuer doctor cannot void (unless SUPER_ADMIN)", "P0", "RBAC",
          "Cert issued by Doc A.", "DOCTOR B",
          "void",
          "1. Void.",
          "403. SUPER_ADMIN can void any.",
          "POST void"),
        c("TS-13-015", "Void Twice", "Already voided → 409", "P1", "Negative",
          "Already VOIDED.", "DOCTOR",
          "void again",
          "1. Void.",
          "409.",
          "POST void"),
        c("TS-13-016", "Send", "Send ISSUED cert via WhatsApp", "P1", "Positive",
          "ISSUED. Patient phone ≥10.", "DOCTOR / RECEPTIONIST",
          "send",
          "1. Send.",
          "PDF outbound. PRINT_SUMMARY_ROLES allowed.",
          "POST .../send"),
        c("TS-13-017", "Send Voided", "Cannot send VOIDED certificate", "P1", "Negative",
          "VOIDED cert.", "DOCTOR",
          "send",
          "1. Send.",
          "Rejected — ISSUED only.",
          "POST send"),
        c("TS-13-018", "List Detail", "List and detail pages show certs", "P1", "Positive",
          "Issued certs exist.", "DOCTOR",
          "/certificates and /certificates/[id]",
          "1. Browse.",
          "Visible with type status number.",
          "pages"),
        c("TS-13-019", "PDF", "Certificate PDF renders type-specific fields", "P0", "Positive",
          "Each type issued.", "DOCTOR",
          "Open PDF",
          "1. Verify sick rest dates / fitness fitFor / general purpose.",
          "%PDF; fields present; signature if snapshotted.",
          "medical-certificate-pdf"),
        c("TS-13-020", "Tenant", "Cannot void/send other hospital certificate", "P0", "Security",
          "H4 cert id.", "DOCTOR H1",
          "—",
          "1. Void/send.",
          "404/403.",
          "API"),
    ]
